### ISSUE TITLE
Allow parsing of function invocations (or some kind of comple types) as part of CLI

### ISSUE THREAD

**Issue by laurisvan** [vmware/differential-datalog#1011]
I am new to DDlog and trying to experiment it in domain of work scheduling and time logging domain. I would like to instantiate non-basic-type inputs (such as TzDateTimes and Uuids) from within CLI (so that I can verify that it works for my domain), but fail to do it.

The inputs are in form of

```
import time as time
import uuid as uuid

/* Input types */
input relation Assignment(
  id: uuid::Uuid,
  assignmentTypeId: uuid::Uuid,

  startsAt: time::TzDateTime,
  endsAt: time::TzDateTime
)

input relation AssignmentType(
  id: uuid::Uuid,

  name: string
)

input relation BalanceWallet(
  id: uuid::Uuid,

  startsAt: time::TzDateTime,
  endsAt: time::TzDateTime
)

input relation BalanceWalletType(
  id: uuid::Uuid,
  assignmentTypeIds: Set<uuid::Uuid>,

  startsAt: time::TzDateTime,
  endsAt: time::TzDateTime
)
```

but I fail to load the data with CLI inputs, such as
```
insert Assignment(
  uuid::parse_str("a3e4811e-bcdb-4418-b0a7-aa3d8f5df9eb"),
  uuid::parse_str("a3e4811e-bcdb-4418-b0a7-aa3d8f5df9eb"),
  time::parse_from_rfc3339("2021-06-27T12:02:05.683Z"), 
  time::parse_from_rfc3339("2021-06-27T12:02:05.683Z")
);
```

The input above fails with `Invalid input: <whatever the line input is>`. Most likely I've understood the concepts wrong and would require a bit of guidance on how to deal with such inputs? I'd really like to input the UUIDs as strings and times as rfc3339. How should I do that?

**Comment by ryzhyk** [comment]
Hi @laurisvan!  The CLI does not currently support function invocations, but if you'd like your program to accept strings as input, your best bet is to add input relations with appropriate signatures along with rules to convert input strings into UUIDs/dates, e.g.,:

```
import uuid as uuid
import time as time

// Input relation contains strings only.
input relation AssignmentInput(
  id: string,
  assignmentTypeId: string,
  startsAt: string,
  endsAt: string
)


// Successfully parsed inputs are stored in this relation.
relation Assignment (
  id: uuid::Uuid,
  assignmentTypeId: uuid::Uuid,
  startsAt: time::TzDateTime,
  endsAt: time::TzDateTime
)

// Convert an instance of AssignmentInput into Assignment; returns an error if
// parsing fails.  Note that we take advantage of the fact that DDlog generates
// type declarations for each user-defined relation, so we can use `Assignment`
// and `AssignmentInput` as types.
function parse_assignment(inp: AssignmentInput): Result<Assignment, string>
{
    Ok{
        Assignment {
            .id = uuid::parse_str(inp.id)?,
            .assignmentTypeId  = uuid::parse_str(inp.assignmentTypeId)?,
            .startsAt = time::tz_datetime_parse_from_rfc3339(inp.startsAt)?,
            .endsAt = time::tz_datetime_parse_from_rfc3339(inp.endsAt)?
        }
    }
}

// Stores results of parsing.
relation ParsedAssignment(parsed: Result<Assignment, string>)

ParsedAssignment(parse_assignment(assignment)) :-
    assignment in AssignmentInput().

// This relation is used to report parse errors to the user.
output relation ParseError(err: string)
ParseError(e) :- ParsedAssignment(Err{e}).

// Finally, store successfully parsed inputs in Assignment.
// Note the square brackets syntax on the left, which allows assigning the
// entire record rather than individual fields (see tutorial for more details:
// https://github.com/vmware/differential-datalog/blob/master/doc/tutorial/tutorial.md#explicit-relation-types).
Assignment[a] :- ParsedAssignment(Ok{a}).
```

**Comment by laurisvan** [comment]
Hi,

This sounds clear and I was thinking about a similar solution. Now that this converts the inputs to simple types, I believe these could be easily prototyped by JSON input. I did not find examples on deserializing arrays of datas (the tests were more or less testing the deserialization of different simple types) - is there a sample I could check from?

And now that I got your attention, let me share how I hoped to use this. We have a lot of this computation both in our application side (heavy browser application) and server-side (currently Node.js), and was thus hoping to create a WASM build and some kind of driver in the spirit of current Go/Java/Rust drivers. I understood some WASM support was merged in May, but I still don't fully understand how how it plays driver-wise.

**Comment by ryzhyk** [comment]
The JSON mapping is pretty straightforward:  structs are serialized into JSON maps, vectors -- into JSON arrays, strings and integers are JSON strings and integers respectively, etc.  Let me know if you're stuck and I can come up with a concrete example.

I've never tried compiling to WASM myself, but my colleague @Kixiron has. @Kixiron, any idea what it would take to run DDlog in  Node.js/browser and to build JavaScript bindings?

**Comment by Kixiron** [comment]
I'm not entirely sure honestly, at the very minimum you'd need to make sure to only ever run ddlog with a single worker thread and to put the entire instance into a web worker so that you could actually do things in the main thread. I haven't tried testing or running on wasm since that requires a bunch of extra setup, I just know that as a bare minimum it compiles on wasm

**Comment by laurisvan** [comment]
Thanks for the comments, @Kixiron & @ryzhyk - you rock! I believe my original issue got resolved and got even more answers than I wished for. If there's any changes needed for DDlog, I'll submit a MR.
