### ISSUE TITLE
Performance of DDlogAPI for JAVA

### ISSUE THREAD

**Issue by sdifv** [vmware/differential-datalog#1031]
The test I performed found that for the same input relations, there are some differences in the execution time for the two execution methods of _cli_ and _api (java)_: the api may take more time than the cli. Is this reasonable? Is the additional overhead introduced by api(java) mainly in flatbuffer serialization or deserialization?

**Comment by ryzhyk** [comment]
Yes, flatbufs certainly introduce overhead, although not as bad as the record-based API.  This also depends on how much input data you feed to DDlog.  Applications with large input data sets and simple rules will see greater impact.  I'll be happy to looks at code/benchmark results if it helps.
