### ISSUE TITLE
Command Language does not support insertion of records to a relation with different name

### ISSUE THREAD

**Issue by qishen** [vmware/differential-datalog#1032]
Hi, I didn't see the syntax support in Command Language Reference that can insert a record of a certain type to a relation with a different name for example if we have a relation like `input relation Record2[Record]` and it only works when both relation and type definition have the same name.

```bash
echo first around:;
start;
insert Node(1),
commit dump_changes;
```

**Comment by ryzhyk** [comment]
You should be able to write:

```
insert Record2[Record{1,2,3}],
```
