### ISSUE TITLE
DDlog java files missing licenses

### ISSUE THREAD

**Issue by amytai** [vmware/differential-datalog#1047]
All source code files under `differential-datalog/java/` are missing MIT License headers.

**Comment by mbudiu-vmw** [comment]
@lalithsuresh apparently some files you added actually have a BSD license. Everything else is MIT.
Is there a reason for this? Could we change them to MIT as well?

**Comment by lalithsuresh** [comment]
My bad, that was my IDE auto-inserting the license header I'd configured for another project.
