### ISSUE TITLE
Feature request: DDlogRecord cloning API

### ISSUE THREAD

**Issue by amytai** [vmware/differential-datalog#1097]
Currently, there's no way to clone a DDlogRecord via the Java API. This means that any function that wants to save a DDlogRecord via a callback (through functions such as commit_dump_changes or dump_index) must manually unpack the record into some alternate in-memory format.

Requesting that DDlogRecord cloning / deep-copy be implemented natively and then exposed in the Java interface.

**Comment by mbudiu-vmw** [comment]
@ryzhyk this requests asks for making a deep copy of ddlog_record and exposing that in the C API.
This arises in the following case: look up a record using an index, and then delete the record from the relation.
Today the record only exists for the duration of the callback, so one needs to clone it.
Am I right that it's enough to just call clone() in rust to achieve that?

**Comment by ryzhyk** [comment]
Yes, that's correct.
