### ISSUE TITLE
Java DDlogAPI can't compile in different directory

### ISSUE THREAD

**Issue by amytai** [vmware/differential-datalog#1128]
Calling `DDlogAPI::compileDDlogProgram` from a directory that isn't `$DDLOG_HOME/sql` fails because of [this line](https://github.com/vmware/differential-datalog/blob/2fce9e84d1049bcd9c61523af5554d0489394418/java/ddlogapi/DDlogAPI.java#L922) in DDlogAPI.java.

I believe `System.getProperty(user.dir)` gets the directory where `java` is being executed, not the directory of the source file.
I think the right fix is to replace that line with
```
String currentDir = System.getEnv("DDLOG_HOME") + "/sql";
```
but I am not certain, as DDlogAPI has undergone some refactoring recently.

**Comment by mbudiu-vmw** [comment]
I suspect you just have to supply DDLOG_HOME/sql as a library.

**Comment by mbudiu-vmw** [comment]
It the libraries that you supply to compileDDlogProgram are relative paths, they are considered relative to user.dir. Just make sure that these paths are correct (or make them absolute). I think that should resolve this problem.

**Comment by amytai** [comment]
You're right, that fixes the problem. Update to DDlogHandle at PR #1132
