### ISSUE TITLE
Unknown variable in Negations statement

### ISSUE THREAD

**Issue by sdifv** [vmware/differential-datalog#1137]
Since negation sematic is implemented by antijoin, where the match process only focus on common attributes in two relations. But I found if a negated statement contains a unique attribute that not appearing in previous relations，there will arise an "Unknown variable" error. For example the following code:
```
input relation Link(node1: string, node2: string)
input relation Filter(node: string, src_node: string, dst_node: string, idx: u32)

output relation Reach(src_node: string, dst_node: string)

Reach(src_node, dst_node) :-
    Link(src_node, dst_node),
    not Filter(src_node, src_node, dst_node, idx).
```
So, the existence of `idx` does not affect the calculation, why can't it appear? Maybe this attribute information will be used later

**Comment by ryzhyk** [comment]
Since `not` represents the non-existence of a record, there is no way to bind `idx` to a value.  In other words, it cannot be used later because there is nothing to use. You can replace `idx` with `_` to make the error go away.

**Comment by sdifv** [comment]
Yes, the `not statement` is not need for positive derivation, but if I want to capture the details when a `not statement` causing a tuple to be deleted, is there any recommended way?

**Comment by ryzhyk** [comment]
Can you give an example of the desired behavior, including input and expected output table contents?

**Comment by Kixiron** [comment]
If I understand correctly, what you probably want is something like this:
```prolog
ReachElim(src_node, dst_node, idx) :-
    Link(src_node, dst_node),
    Filter(src_node, src_node, dst_node, idx).
    
Reach(src_node, dest_node) :-
    Link(src_node, dest_node),
    not ReachElim(src_node, dest_node, _).
```
This allows you to remove things as you'd expect while still retaining the knowledge of who was removed by what. This is basically just an additional semijoin on the filtering criteria to collect whatever is removing elements from your relation

**Comment by sdifv** [comment]
> If I understand correctly, what you probably want is something like this:
> 
> ```prolog
> ReachElim(src_node, dst_node, idx) :-
>     Link(src_node, dst_node),
>     Filter(src_node, src_node, dst_node, idx).
>     
> Reach(src_node, dest_node) :-
>     Link(src_node, dest_node),
>     not ReachElim(src_node, dest_node, _).
> ```
> 
> This allows you to remove things as you'd expect while still retaining the knowledge of who was removed by what. This is basically just an additional semijoin on the filtering criteria to collect whatever is removing elements from your relation

Ok! I think it's worth a try, thank you
