### ISSUE TITLE
(Question) Iterating over vector elements in the body of a rule

### ISSUE THREAD

**Issue by tatiana-s** [vmware/differential-datalog#1142]
### Is your feature request related to a problem? Please describe.

Say I have the following as a simplified example:
```
typedef ID = signed<32>

input relation Program(id: ID,  body_ids: Vec<ID>)
…

output relation OkProgram(id: ID)
output relation OkBody(id: ID)
…
```

I essentially want to query  for `Program`s for which the `OkBody` rule holds for all IDs in the vector (in practice I have more input relations and rules etc.).

### Describe the solution you'd like

In an imperative style I would do something like this:
```
OkProgram(id) :-
        Program(id, body_ids),
	for (body_id in body_ids)
		OkBody(body_id).

OkBody(id) :- …
```

### Describe alternatives you've considered

How would you best go about doing this? I haven’t found an obvious way of doing it by reading through the tutorial/language reference but I am likely missing something (I can see how this could be done if I was using a function/closure but not with rules).

**Comment by ryzhyk** [comment]
@tatiana-s, does the following do what you're after?

```
typedef ID = signed<32>

input relation Program(id: ID,  body_ids: Vec<ID>)
input relation OkBody(id: ID)

relation ErrProgram(program: ID, body: ID)

// Programs with at least one body that violates OkBody.
ErrProgram(program, body) :-
    Program(program, bodies),
    var body = FlatMap(bodies),
    not OkBody(body).

output relation OkProgram(program: ID)

// All programs not in ErrProgram are Ok.
OkProgram(program) :-
    Program(program, _),
    not ErrProgram(program, _).
```

**Comment by ryzhyk** [comment]
Here is a more heavy-handed implementation that uses aggregation.

```
OkProgram(program) :-
    Program(program, bodies),
    var num_bodies = bodies.len(),
    var body = FlatMap(bodies),
    OkBody(body),
    // Count distinct bodies of `program` that satisfy `OkBody`.
    var num_ok_bodies = body.group_by((program, num_bodies)).count_distinct(),
    // Check that the number of ok-bodies is the same as the number of all bodies.
    // CAVEAT: we assume that all elements of `bodies` are distict.
    num_ok_bodies == num_bodies.

// The previous rule does not match programs with 0 bodies.  We need to
// handle this case separately.
OkProgram(program) :- Program(program, vec_empty()).

```

**Comment by tatiana-s** [comment]
@ryzhyk Yes, the first approach works (and maybe the second one will come in hand at a later point), thank you!
