### ISSUE TITLE
Handle numerical overflows in debug builds

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#115]
Rust debug builds panic on numerical overflows, crashing a worker thread and causing an infinite loop in `program.rs`.  Possible solutions:

- use `Wrapping` types to avoid overflows
- disable overflow checking in debug builds
- properly crash DDlog instead of putting it in an infinite loop

**Comment by mbudiu-vmw** [comment]
The semantics of DDlog should allow wrapping (probably, we should spell this in the reference implementation). So this should be mostly about whatever other counters the runtime maintains.
We could also add a new set of arithmetic operations that does not wrap. 
P4 has for example |+| for saturated addition (which is something different than no wrapping, but I like the operator).

**Comment by ryzhyk** [comment]
We are now using wrapping arithmetic, so this should be fixed
