### ISSUE TITLE
Benchmark dataset avaliable?

### ISSUE THREAD

**Issue by StarGazerM** [vmware/differential-datalog#1175]
Hi, I am wondering is there is any benchmark dataset avalible for test program like the one under test folder including some souffle's program analysis?

**Comment by mihaibudiu** [comment]
This software has not received updates for 3 years.
For Souffle we used to programs from their own repository, with their own datasets, but I don't think we ever benchmarked them head to head.

**Comment by StarGazerM** [comment]
thank you so much!
