### ISSUE TITLE
syntax to select tuple fields by number

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#13]
x == (x,y).0
y == (x,y).1
z == (x,y,z).2
...

**Comment by mbudiu-vmw** [comment]
I am not sure this syntax will work if we want to support FP: `.1` may be ambiguous as a floating point number. How about something like `.f0`?

**Comment by ryzhyk** [comment]
I don't think it's ambiguous, as `.1` will always follow another expression, e.g., in `x .1` there is no valid interpretation of `.1` as a number and in `x + .1` there is no way to interpret `.1` as a field access.

`.f0`, on the other hand, is ambiguous, since we don't know during parsing if it refers to a field of a struct or a tuple.

**Comment by mbudiu-vmw** [comment]
I don't think .f0 is ambiguous at all, the type-checked can decide what it means.
But I will try .1. Hopefully we won't be sorry in the long term.

**Comment by ryzhyk** [comment]
I think you want the parser to be similar to `postField`.

**Comment by ryzhyk** [comment]
> I don't think .f0 is ambiguous at all, the type-checked can decide what it means.

Sure, but given the current structure of the compiler this will require another pass of program re-writing, which I hope to avoid.

If we ever want to support FP numbers, we'll have other problems to, e.g., the dot in the end of a rule.  Sometimes these can be solved by doing more lookahead.
