### ISSUE TITLE
Check Rust compiler version

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#175]

**Comment by d-e-s-o** [comment]
@ryzhyk Can you provide a few details what this issue is about please?

**Comment by ryzhyk** [comment]
DDlog (and especially DD) require a relatively recent version of Rust. I don't think there is currently a way to specify supported `rustc` versions in `Cargo.toml`. Alternatively, `stack test` could complain when the compiler is too old.  This is a low-priority issue, though.

**Comment by ryzhyk** [comment]
duplicate of #471
