### ISSUE TITLE
Add an arg_min function to the library

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/differential-datalog#226]
Signature is `arg_min<V, C>(it: iterable<V>, fn: function(v: V): C): V`
where `C` is some type that supports comparisons.

**Comment by mbudiu-vmw** [comment]
You may need a second function to apply to the result at the end too.
In the lcp example both functions would be projections of a tuple.
Can we write tuple projections in ddlog?

**Comment by ryzhyk** [comment]
There are no higher-order types in DDlog, so you cannot pass functions as arguments.

**Comment by mbudiu-vmw** [comment]
Well, then you can just specialize it for tuples with two elements.
