### ISSUE TITLE
Address Clippy warning

### ISSUE THREAD

**Issue by remysucre** [vmware/differential-datalog#274]
Clipply warnings may be addressed at least for rust/template. For generated code, there should be a way to selectively turn off clippy.

**Comment by ryzhyk** [comment]
Are there more warnings left? Is there a way to integrate Clippy to run during `cargo build` or `cargo test` or otherwise integrate it into the build process?

**Comment by remysucre** [comment]
There are a lot more none-critical warnings. I just found a tool that auto-applies warnings, which should speed this up a lot (we should review the changes of course) https://github.com/rust-lang-nursery/rustfix. Yes there's a way to have this in the build process (https://github.com/mwillsey/egg/blob/master/check.sh) I can give it a try

**Comment by remysucre** [comment]
Next steps are: 
1. fix more warnings
2. have clippy run as part of the build
3. run `cargo fmt`

**Comment by d-e-s-o** [comment]
Let me take this one. I just enabled `rustfmt` (for https://github.com/vmware/differential-datalog/issues/338) and clippy should be similar in many respects.

**Comment by d-e-s-o** [comment]
`clippy` is now running as part of Travis and checking various crates. Here are the remaining tasks I see:
- fix the individual lints we currently white list or investigate whether to keep the contentious ones in the white list:
  - [ ] clippy::char_lit_as_u8
  - [ ] clippy::many_single_char_names
  - [ ] clippy::enum_variant_names
  - [ ] clippy::expect_fun_call
  - [ ] clippy::extra_unused_lifetimes
  - [ ] clippy::for_kv_map
  - [ ] clippy::get_unwrap
  - [ ] clippy::into_iter_on_ref
  - [ ] clippy::just_underscores_and_digits
  - [ ] clippy::let_and_return
  - [ ] clippy::map_clone
  - [ ] clippy::needless_return
  - [ ] clippy::new_without_default
  - [ ] clippy::ptr_arg
  - [ ] clippy::ptr_offset_with_cast
  - [ ] clippy::redundant_closure
  - [ ] clippy::should_implement_trait
  - [ ] clippy::trivially_copy_pass_by_ref
  - [ ] clippy::single_match
  - [ ] clippy::type_complexity
  - [ ] clippy::unreadable_literal
- [ ] push white listing to the individual crates (we should not have to touch `.travis` for such policy decisions)
  - that will also allow us to run the same `clippy` command locally more easily

**Comment by d-e-s-o** [comment]
Let me close this issue as there isn't anything actionable left here and we are in pretty good shape.
