### ISSUE TITLE
vec_push_imm implemented as std_vec_insert_imm

### ISSUE THREAD

**Issue by hessammehr** [vmware/differential-datalog#284]
The following (simplified) path finding code compiles without issue but the resulting Rust code fails to build because of missing `std_vec_push_imm`.

```
input relation Edge(x: string, y: string)
output relation Path(x: string, y: string, path: Vec<string>)
Path(x, y, vec_empty()) :- Edge(x, y).
Path(x, y, vec_push_imm(v, z)) :- Path(x, z, v), Edge(z, y).
```

It looks like `std.rs` defines this function under `std_vec_insert_imm`. In fact the following builds and runs as expected

```
extern function std_vec_insert_imm (v: Vec<'X>, x: 'X): Vec<'X>

input relation Edge(x: string, y: string)
output relation Path(x: string, y: string, path: Vec<string>)
Path(x, y, vec_empty()) :- Edge(x, y).
Path(x, y, std_vec_insert_imm(v, z)) :- Path(x, z, v), Edge(z, y).
```

I can send a PR with the signatures matching one or the other name if it makes sense.

**Comment by ryzhyk** [comment]
Many thanks for reporting! No need for PR. I'll fix it and merge the fix once it passes tests.

**Comment by ryzhyk** [comment]
Fixed.

Thanks again, and would love to hear about your DDlog use case.

**Comment by hessammehr** [comment]
@ryzhyk No problem, thanks for the quick response and fix!

I've been sketching a mini "compiler" for orchestration of liquid handling robotics (code [here](https://github.com/hessammehr/liquid_rules_ddlog)) being fairly sure this was going to be impossible in Datalog (as opposed to Prolog) but the rich type system in differential-datalog and access to Vec/Map/Set saved the day. I am also really excited about the possibility of recursive data types in the future.

**Comment by hessammehr** [comment]
Also, please feel free to mention me on easier issues that you might want a hand with.

**Comment by ryzhyk** [comment]
> @ryzhyk No problem, thanks for the quick response and fix!
> 
> I've been sketching a mini "compiler" for orchestration of liquid handling robotics (code [here](https://github.com/hessammehr/liquid_rules_ddlog)) being fairly sure this was going to be impossible in Datalog (as opposed to Prolog) but the rich type system in differential-datalog and access to Vec/Map/Set saved the day. I am also really excited about the possibility of recursive data types in the future.

Interesting! This is at least the second use case for recursive types that we know of. Unfortunately, it will probably take us a month or two to get to it, as we need to finish implementing several other urgent features first.
