### ISSUE TITLE
`HDDlog::dump_table` and `HDDlog::commit_dump_changes` must return iterators

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#287]

**Comment by ryzhyk** [comment]
The way to do `dump_table()` is probably to return an iterator whose lifetime is bound to that of `HDDlog`.

**Comment by remysucre** [comment]
I tried this and the lifetime seems to be bound to that of `HDDlog.db` and not `HDDlog`. Is there a way to hook those up?

**Comment by remysucre** [comment]
To handle this properly one may need to implement a special iterator for the database, which may complicate the API, thus closing.
