### ISSUE TITLE
FlatBuffers error when relations contain a primitive type

### ISSUE THREAD

**Issue by remysucre** [vmware/differential-datalog#309]
I got the following error when running `stack test` on the following program: 

      compiler tests
        ddd: FAIL (0.07s)
          flatc failed with exit code ExitFailure 1
          stdout:
      
      
          stdout:
          error: /Users/remyw/differential-datalog/test/datalog_tests/ddd_ddlog/flatbuf/flatbuf.fbs:32: 21: error: type referenced but not defined (check namespace): __Bool, originally at: flatbuf.fbs:20

Program: 

    input relation Left[bool]
    output relation Middle[bool]
    Middle[b] :- Left[b].

**Comment by ryzhyk** [comment]
This should be fixed here: https://github.com/ddlog-dev/differential-datalog/tree/flatbuffers2

If you don't want to wait for the PR to land, you can either change your relation signature from
`Left[bool]` to `Left(bool)` or not invoke `ddlog` with `-j` flag (as you don't need Java support).
