### ISSUE TITLE
Tests for the FlatBuffers API

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#312]

**Comment by ryzhyk** [comment]
Some additional test dimensions:
- Move type declarations into a module to test for namespace-related issues
- Bit vectors >128 bit wide
- Wrap various types in type aliases
- Test user-defined generic types

**Comment by mbudiu-vmw** [comment]
I can work on some of these.

**Comment by ryzhyk** [comment]
Thanks, that would be great! I'll push a PR soon and will switch to writing documentation. You can pick it up from there.
