### ISSUE TITLE
Flatbuf does not work correctly for negative values.

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/differential-datalog#315]
```
input relation DI(d: signed<16>)
output relation DO(d: signed<16>)
DO(d) :- DI(d).
```

in Java:

```Java
        flatbuf_testUpdateBuilder builder = new flatbuf_testUpdateBuilder();
        builder.insert_DI((short)-5);
```

The output value in DO is 0 instead of -5.

**Comment by mbudiu-vmw** [comment]
Same problem with BigInteger.

**Comment by ryzhyk** [comment]
This was actually a bug in `DDlogRecord.toString`, which was in turn caused by the completely broken C/Java API for integers.  The fix is on its way: https://github.com/ddlog-dev/differential-datalog/commit/840a5b2d346ee91c8f0fac9d72bb7c488786959c
