### ISSUE TITLE
Java APIs generated for some datatypes are not documented

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/differential-datalog#318]
For example, the fact that 
`input relation JI(a: (bool, bit<8>, string))` generates a Java API involving a class named
`Tuple3__bool__bit_8___string`

**Comment by ryzhyk** [comment]
Frankly, none of the generated APIs are documented at the moment.  Such documentagtion should be added to the last section of `doc/java_api.md`.

**Comment by ryzhyk** [comment]
@mbudiu-vmw , ok to close this?
