### ISSUE TITLE
Events Processing

### ISSUE THREAD

**Issue by prepor** [vmware/differential-datalog#320]
Hi. Very interesting project, thank you. I'm thinking about applying it to systems where inputs are mostly events. Event is a sort of instant fact, which could trigger computations and new facts. An example of an event is the user's click

Other systems, as I know, have special logic for such use cases. For example:

Eve has two types of RHS: bind or commit. Bind works very like IDB rules. Commit adds new facts unconditionally, committed facts will be valid even after retracting of events that committed them.

Logicblox has pulse predicates.

Does DDLog have something similar? Or any plans to add? Or some workarounds?

Thank you.

**Comment by ryzhyk** [comment]
I am afraid, DDlog is not really suitable for writing interactive applications.  Technically, it is possible to model events as input tables with a timestamp column.  Since DDlog is incremental, each new event will trigger computation, potentially producing new outputs.  Deleting an event will however delete facts derived from it.  Keeping events around, on the other hand, will consume memory.

Having said that, it would help to know more about your application to tell if  DDlog might be a good match for it.

**Comment by prepor** [comment]
> Deleting an event will however delete facts derived from it

Yes, and this is a "problem" :)

There is no "application" currently, I'm just looking for new ways to write applications, including UI. A more declarative, extendable and introspectable way. I really liked Eve approach (https://github.com/witheve/eve-native).

I'm not sure how hard it could be to add such semantic to DDLog, looks like Logicblox guys spent a lot of time to think about it (https://developer.logicblox.com/content/docs4/core-reference/html/index.html#rules-events).

But ok, maybe it would be good enough to have an additional layer in interactive apps, which will translate events into facts.

BTW, as I see, DDLog already doesn't store input relations which doesn't have derived facts. It's a good start :)

**Comment by mbudiu-vmw** [comment]
Our underlying framework differential dataflow has been used successfully in many event driven applications. https://github.com/TimelyDataflow/differential-dataflow

**Comment by prepor** [comment]
@mbudiu-vmw yeh, sure, differential-dataflow's model is totally suited for events processing. The question is whether event processing logic can be represented using declarative language like DDLog. It could make DDLog much more general-purpose language, don't you think so?

**Comment by prepor** [comment]
and could you please provide examples of such applications?

**Comment by ryzhyk** [comment]
Actually I'm not sure DD has been used in UI or similar applications that require interactive responsiveness. In fact, it is optimized for batch processing, which might be the real problem here.

**Comment by prepor** [comment]
@ryzhyk in DD paper there is an interactive UI application as an example:
http://michaelisard.com/pubs/differentialdataflow.pdf

> In this demonstration, we show how Naiad can compute the
strongly connected component (SCC) structure of the mention graph extracted from a time window of the Twitter stream, and then extend this to build an interactive application that uses Naiad to track the evolution of these components as the window slides back and forth in time.

**Comment by prepor** [comment]
and there are also some experiments with DD and UI (via WASM!) https://github.com/comnik/functional-differential-programming

**Comment by ryzhyk** [comment]
The example from the Naiad paper is interactive in the sense that by using incremental computation it reduces compute time from minutes or hours to seconds or tens of milliseconds (hypothetically speaking, I don't remember the actual numbers in the paper), which is fast enough to integrate in an interactive ui that responds to user actions in real time. But I don't think differential is actually used to process ui events like mouse movement or key presses.

In my experience, differential is quite inefficient when handling small updates that are not grouped into batches.

There are all kinds of tricks one could come up with to encode event-based logic in dd or ddlog, but I am worried that in the end of the day the performance won't be great.

Another important question is whether your use case involves incremental computation. DD and ddlog are most useful in applications that update their outputs incrementally. If your problem has this flavor, then it might be worth looking more closely into it. On the other hand, I don't think that either DD or ddlog can be useful as generic ui toolkits.

**Comment by prepor** [comment]
> as the window slides back and forth in time

I think it means that user suppose to slide this window :)

Ok, thank you for your replies, as I understand Event Processing is out of the scope of this project (and possibly DD). Thank you
