### ISSUE TITLE
Unmodified code recompiles if it depends on generated crate

### ISSUE THREAD

**Issue by remysucre** [vmware/differential-datalog#325]
In a crate that depends on the generated crate from a DDlog program, running `cargo build` recompiles the client code and the generated crate even if nothing was changed. Steps to replicate: 

1. run `ddlog -i copy.dl -L../../lib` under `test/datalog_tests`
2. run `cargo build` under `test/datalog_tests/copy_ddlog`
3. repeat running `cargo build` under `test/datalog_tests/api_test`

However, if the DDlog crate was generated by `stack test`, the issues seems to disappear. So try removing the DDlog crate before trying to replicate.

**Comment by ryzhyk** [comment]
I fixed this type of issue recently (but maybe not exactly this one).  Have you merged the latest master?

**Comment by remysucre** [comment]
Yes I did merge it

**Comment by ryzhyk** [comment]
One more question: why do you want to recompile copy_ddlog by hand. Shouldn't it get compiled automatically as api_test dependency?

**Comment by remysucre** [comment]
You're right, I don't really need to compile copy_ddlog separately. But skipping that doesn't prevent rebuilding api_test

**Comment by remysucre** [comment]
I see what's happening: since I'm not using flatbuff, `flatbuf.rs` and `flatbuf_generated.rs` are not there. Commenting out the `rerun-if-changed` lines in `build.rs` prevents the rebuild. This could be a cargo bug, and we could work around it if we generate the build script depending on the flag.

**Comment by ryzhyk** [comment]
Thanks for the diagnostic. It is my bug, as I generate explicit list of depenencies in build.rs. Will fix soon.
