### ISSUE TITLE
Usage of rustfmt

### ISSUE THREAD

**Issue by d-e-s-o** [vmware/differential-datalog#338]
I was under the impression that issue had been brought up in the past in the context of improved usage of tooling (out of which the usage of `clippy` came), but I can't seem to find it: should we use [`rustfmt`](https://github.com/rust-lang/rustfmt) to automate the formatting of Rust code? I feel that at least newly checked in code should be formatted in a standard way, so as to reduce the amount of nitpicking in pull requests and to allow focusing on the more relevant parts.

`rustfmt` can be configured fairly freely (and the config file could be checked in), but I would also be fine with the defaults. As a later step (if we find it to be useful and want to enforce it more widely), we could hook it up in Travis.

Are there opinions on the matter?

**Comment by ryzhyk** [comment]
Yes, I would like to integrate both rustfmt and clippy, but haven't yet spent any time figuring out the best way to do so.  Ideally, they should both run as part of the build process (with the build failing if one of the two is unhappy).  Happy to discuss the details if you feel like taking on this issue.

**Comment by d-e-s-o** [comment]
Thanks! Okay, let me park this issue with me for now. Right now I just wanted to gauge whether there is any opposition ;)

**Comment by d-e-s-o** [comment]
Merged as https://github.com/vmware/differential-datalog/pull/347.
