### ISSUE TITLE
CLI: Comments don't work properly inside a transaction

### ISSUE THREAD

**Issue by d-e-s-o** [vmware/differential-datalog#358]
I noticed that handling of comments in transactions in the CLI is seemingly broken (at least it does not seem correct to me).

Assuming the `playpen` example from the tutorial, consider the following working workflow:
```
>> start;
>> insert Word1("Hello,", CategoryOther);
>> insert Word2("world!", CategoryOther);
>> commit;
insert(+1) 0 Phrases{.phrase = "Hello, world!"}
>> dump;
Phrases:
Phrases{"Hello, world!"}
```

But the moment I insert a comment, the transaction is seemingly no longer committed properly (or at least I don't get the expected out until quitting the program):
```
>> start;
>> insert Word1("Hello,", CategoryOther);
>> insert Word2("world!", CategoryOther);
>> # This is a comment!
>> commit;
>> dump;
>>
CTRL-D
insert(+1) 0 Phrases{.phrase = "Hello, world!"}
```

I initially thought that may be due to https://github.com/vmware/differential-datalog/commit/4dc0cd152bc91b0914c78ab74250c277c2a19c01 but it seems the problem exists without that commit as well.

**Comment by ryzhyk** [comment]
I am guessing we should be checking for end of line, not new-line (`\n`) in the comment parser. Will try to fix now...

**Comment by ryzhyk** [comment]
https://github.com/ddlog-dev/differential-datalog/commit/e6e50494223eb27ec48c927bb7cbae83b01b1c4c
