### ISSUE TITLE
Add a flag to label all non-input relations as `output`.

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#391]
This is helpful when debugging a large program when the user wants to dump the contents of some relations without re-compiling the whole thing.

**Comment by dceara** [comment]
@ryzhyk @mbudiu-vmw 

How is this supposed to work? If I add:

```
$(AM_V_GEN)ddlog -i $< -L @DDLOG_LIB@ --output-internal-relations --output-input-relations=ZZZ
```

To the make rule that runs `ddlog`:
https://github.com/ovn-org/ovn/blob/ddlog-dev-v2/northd/automake.mk#L111

I get the following error:
```
ddlog -i northd/ovn_northd.dl -L /home/dceara/tools/ddlog/lib/ --output-internal-relations --output-input-relations=ZZZ
ddlog: error: /home/dceara/git-repos/ovn/northd/OVN_Northbound.dl:41:1-54:1: Only input relations can be declared with a primary key
make: *** [northd/ovn_northd_ddlog/target/release/libovn_northd_ddlog.a] Error 1
```

I assume it's because the input relation has a primary key. `OVN_Northbound.dl:41`:
```
input relation ACL (
    _uuid: uuid,
    name: Set<string>,
    priority: integer,
    direction: string,
    __match: string,
    action: string,
    log: bool,
    severity: Set<string>,
    meter: Set<string>,
    external_ids: Map<string,string>
)
primary key (x) x._uuid
```

Am I missing something?

Thanks,
Dumitru

**Comment by ryzhyk** [comment]
It's a bug. Thanks for reporting. We'll create a fix.

**Comment by dceara** [comment]
> It's a bug. Thanks for reporting. We'll create a fix.

@ryzhyk, thanks!

**Comment by mbudiu-vmw** [comment]
I will have a fix right away.

**Comment by ryzhyk** [comment]
I'm already on it.

**Comment by mbudiu-vmw** [comment]
I have a fix and a test, just running the tests now.

**Comment by mbudiu-vmw** [comment]
We should assign the issue to someone to prevent duplicate work.
