### ISSUE TITLE
--no-print appears to be ineffective on DDlog v0.10.0alpha release

### ISSUE THREAD

**Issue by ekcs** [vmware/differential-datalog#406]
On the DDlog v0.10.0alpha release:
$ ddlog_cli -w 3 --no-print --no-store < ddlog_command_recording
Span:
Span{.entity = 1, .span = [3, 19, 21, 77, 85, 87, 99, 113, 115, 125, 149, 153, 169, 207, 211, 227, 235, 237, 255, 277, 279, 281, 309, 325, 327, 339, 355, 361, 365, 381, 385, 395, 407, 431, 483, 487, 495, 519, 521, 531, 545, 563, 565, 583, 607, 609, 619, 635, 653, 663, 681, 683, 691, 719, 729, 731, 733, 765, 821, 849, 851, 855, 865, 885, 897, 903, 913, 919, 923, 927, 945, 951, 963, 981, 989, 1013, 1023, 1039, 1075, 1085, 1107, 1129, 1131, 1133, 1141, 1155, 1173, 1183]}: +1
Span{.entity = 9, .span = [1177]}: +1
Span{.entity = 33, .span = [5]}: +1
Span{.entity = 35, .span = [5]}: +1

**Comment by ryzhyk** [comment]
@ekcs , it looks like the `ddlog_command_recording` file contains `commitDumpChanges` commands.  The `--no-print` flag does not  affect those. If you also want `commitDumpChanges` to be quiet, you'll need to add the `--no-delta` switch to the command line.

**Comment by ekcs** [comment]
Ah got it thanks!
