### ISSUE TITLE
Support compiling a schema and loading the shared library from Java at runtime

### ISSUE THREAD

**Issue by lalithsuresh** [vmware/differential-datalog#486]
Something similar to https://github.com/lalithsuresh/differential-datalog/blob/sql/sql/src/test/java/ddlog/RuntimeTest.java#L101, but which can also invoke the rust compiler and load the shared library.

This would greatly simplify integrating into projects where there are a large number of schemas as part of tests.

**Comment by mbudiu-vmw** [comment]
This was fixed by #488
