### ISSUE TITLE
Poor type inference with integer constants

### ISSUE THREAD

**Issue by blp** [vmware/differential-datalog#567]
The compiler rejects the following program ("Incompatible types bit<64> and bigint"):

> relation R(a: Set<string>)
> R(a) :- R(a), set_size(a) > 1.

It accepts it if 1 is changed to 64'd1, e.g.:

> relation R(a: Set<string>)
> R(a) :- R(a), set_size(a) > 64'd1.

Possibly related to https://github.com/vmware/differential-datalog/issues/500.
Could be solved by https://github.com/vmware/differential-datalog/issues/77.

**Comment by ryzhyk** [comment]
Grouping type inference-related issues.
