### ISSUE TITLE
Generated CLIs write all output to stderr

### ISSUE THREAD

**Issue by blp** [vmware/differential-datalog#570]
The CLI binaries that ddlog produces write all of their output to stderr rather than the more conventional stdout. This is surprising and it means that to filter them or pass them through, e.g., `less`, one must first clone stdout to stderr with `2>&1`.

It would be more conventional to write regular output (like the output of `dump`, etc.) to stdout, and actual errors to stderr.

**Comment by ryzhyk** [comment]
The exact behavior of CLI binaries is as follows:
- All commands that produce output (`dump`, `commit dump_changes`, `echo`, `timestamp`) write their output to stdout.
- In addition, when the CLI is run without the `--no-print` flag, it prints changes to output relations as they occur inside DDlog. This output is written to stderr, as I see it as a low-level debugging mechanism (most real consumers should use `commit dump_changes` to observe changes to output relations).

Do you think this behavior is not reasonable?

I think it is time to make `--no-print` the default: it was originally introduced before we had `commit dump_changes` and is almost never useful any longer.

**Comment by blp** [comment]
It seems like unusual behavior to me because it is voluminous, does not signify errors, and would distract from actual errors.

Suppressing it by default seems reasonable to me.

**Comment by d4hines** [comment]
FYI, the tutorial uses `commit` and indicates you'll see the diff. But presently, you won't see the diff unless you do `commit dump_changes`. https://github.com/vmware/differential-datalog/blob/master/doc/tutorial/tutorial.md#running-the-hello-world-program
