### ISSUE TITLE
New User Experience

### ISSUE THREAD

**Issue by joeattueyi** [vmware/differential-datalog#574]
New users trying out introductory examples are likely to meet problems that current documentation cannot help them solve.

One example : compiling `playpen.dl` from the intro leads to compile errors.

`% (cd playpen_ddlog && cargo build --release)
   Compiling types v0.1.0 (/Users/jattueyi/Documents/Play/playpen_ddlog/types)
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)
   --> types/lib.rs:221:5
    |
221 |     impl<T> From<std_Option<T>> for Option<T> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type parameter `T` must be used as the type parameter for some local type
    |
    = note: only traits defined in the current crate can be implemented for a type parameter

error: aborting due to previous error

For more information about this error, try `rustc --explain E0210`.
error: could not compile `types`.

To learn more, run the command again with --verbose.`

**Comment by ryzhyk** [comment]
This is valuable feedback, thank you.  Looks like you have Rust compiler <1.41. We do document this dependency, but we should really be checking rust compiler version automatically.  We have an open issue for that: #471 , but it is quite tricky to do.
