### ISSUE TITLE
"at" syntax for binding variables is not documented

### ISSUE THREAD

**Issue by blp** [vmware/differential-datalog#583]
DDlog supports a variable binding syntax using @, e.g. `peer1@RouterPort{.router = &peer_router}`
creates variables `peer1`  and `peer_router`; the former is bound to `RouterPort{.router = &peer_router}`.

The documentation does not mention or explain this syntax.

**Comment by ryzhyk** [comment]
Fixed in c4374d32f57726d0fc638b37b7c7d94c925dab0e
