### ISSUE TITLE
DDlog gives an incorrect error message

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/differential-datalog#593]
For this program
```
function f(b: Option<bool>): Option<bool> = b

typedef Tagg = Tagg{col:bool}

function agg():Tagg =
  (var any = Some{false}: Option<bool>);
  (Tagg{.col = f(any)})
```

The error generated is:
```
ddlog: error: x.dl:7:16-7:22: Cannot match expected type std.Option<bool> and actual type bool in call to function f (b: std.Option<bool>): std.Option<bool>
```
However, the argument to `f` is definitely correct, it's the result returned from `f` that has the wrong type.

**Comment by ryzhyk** [comment]
That's what this message is supposed to mean. It's just not phrased correctly. I will fix.

**Comment by mbudiu-vmw** [comment]
If it's just a typo I can probably do it too.

**Comment by ryzhyk** [comment]
It might be trickier than that...

**Comment by blp** [comment]
I run into this one from time to time too.

**Comment by ryzhyk** [comment]
Type inference solves this.  Will push a test with the next PR.
