### ISSUE TITLE
Surprising parsing ambiguity between expressions and rules

### ISSUE THREAD

**Issue by blp** [vmware/differential-datalog#603]
This parses OK:

> function myfunc(x: string): string = { x }
> relation &X(x: string)
> &X("foo").

It fails if we swap lines 1 and 2:

> relation &X(x: string)
> function myfunc(x: string): string = { x }
> &X("foo").

with:
> ddlog: Failed to parse input file: "playpen3.dl" (line 3, column 3):
> unexpected '('
> expecting "#", "import", "typedef", "extern", "input", "output", "relation", "index", "function", "transformer", variable name, "&", relation name, "apply", "for" or end of input

**Comment by blp** [comment]
Fixing issue #606 would solve this, if terminators were mandatory.

Another way to solve it would be to make {} a mandatory part of the syntax for functions.

**Comment by ryzhyk** [comment]
Closed via #610
