### ISSUE TITLE
Error on creating the dynamic lib for FFI binding

### ISSUE THREAD

**Issue by RAbraham** [vmware/differential-datalog#605]
Hi,
For learning about C bindings, I was trying to follow the [Go bindings](https://github.com/vmware/differential-datalog/tree/master/go) documentation and I was trying to simulate the `build-ddlog-prog.sh` script.

For the `playpen` example, my steps are:
```
export DDLOGFLAGS="--output-input-relations=O --dynlib"
export DDLOG_LIB=/Users/rabraham/Documents/dev/software/ddlog/lib
rm -rf playpen_ddlog && ddlog -i playpen.dl ${DDLOGFLAGS} -L $DDLOG_LIB  && cd playpen_ddlog && cargo build --release
```

I get the following errors:
```
.....
Compiling types v0.1.0 (/Users/rabraham/Documents/dev/ddlog/playpen_ddlog/types)
Compiling value v0.1.0 (/Users/rabraham/Documents/dev/ddlog/playpen_ddlog/value)
error: expected one of `!`, `(`, `...`, `..=`, `..`, `::`, `=>`, `if`, `{`, or `|`, found `-`
   --> value/lib.rs:179:22
    |
179 |         Relations::O --dynlibWord1 => true,
    |                      ^ expected one of 10 possible tokens

error: expected one of `!`, `(`, `...`, `..=`, `..`, `::`, `=>`, `if`, `{`, or `|`, found `-`
   --> value/lib.rs:307:22
    |
307 |         Relations::O --dynlibWord1 => {
    |                      ^ expected one of 10 possible tokens

error: expected one of `(`, `,`, `=`, `{`, or `}`, found `-`
   --> value/lib.rs:346:7
    |
346 |     O --dynlibWord1 = 0,
    |       ^ expected one of `(`, `,`, `=`, `{`, or `}`

error: expected item, found `-`
   --> value/lib.rs:346:7
    |
346 |     O --dynlibWord1 = 0,
    |       ^ expected item

error: aborting due to 4 previous errors

error: could not compile `value`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Let me know what I'm doing incorrectly or if I'm on the wrong path. Thanks!

**Comment by mbudiu-vmw** [comment]
It looks like the string `"O --dynlib"` is interpreted as a relation name.
The `-L $DDLOG_LIB` flag is no longer necessary.

**Comment by mbudiu-vmw** [comment]
We should probably validate the string passed to `--outout-input-relations`; it should be an uppercase identifier.

**Comment by mbudiu-vmw** [comment]
More precisely, the command passed to ddlog included `--output-input-relations="-O --dynlib"`

**Comment by ryzhyk** [comment]
Regarding the error, the script works for me on Linux in bash. I wonder if this is some kind of Mac issue, but yes, as Mihai explained, `O --dynlib` ended up being interpreted as a single token.

Additionally:
- the `--output-input-relations=O` option is only used for debugging to mirror input relations to the output. You probably don't want to use it otherwise
- `rm -rf playpen_ddlog` is probably not a good idea, as you will end up recompiling generated Rust code from scratch every time
- `-L $DDLOG_LIB` is only optional if you set the `$DDLOG_HOME` environment variable to point to the `differential-datalog` directory.

**Comment by RAbraham** [comment]
I removed `--output-input-relations=O` from the script and it worked. Nice catch about the Mac. I think I should move to Linux because this bites me so often.

Thank you @mbudiu-vmw and @ryzhyk for your quick response :)
