### ISSUE TITLE
Capitalization Rules not Correct

### ISSUE THREAD

**Issue by d4hines** [vmware/differential-datalog#627]
According to this, https://github.com/vmware/differential-datalog/blob/master/doc/tutorial/tutorial.md#capitalization-rules, type names have no restrictions. However, the following didn't compile:
```
typedef axes = x | y
```
This does, however:
```
typedef axes = X | Y
```

**Comment by ryzhyk** [comment]
`X` and `Y` are constructor names, not type names. Constructor names must be capitalized in DDlog. The type name here is `axes`.

**Comment by mbudiu-vmw** [comment]
Technically X and Y are type constructors.
Indeed, the tutorial does not say that they have to be uppercase. We should fix the tutorial.
