### ISSUE TITLE
Question: Representing Type Hierarchies in DDLog

### ISSUE THREAD

**Issue by d4hines** [vmware/differential-datalog#629]
Hello again,
I love DDLog's strong types, but I'm having trouble mapping some concepts between different programming paradigms. My goal is to translate ALM, another logic language, into DDLog. ALM doesn't have types in the FP sense. Rather, it has "sorts" - for example, a particular object might be of the sort `Tables`, which is itself a subset of `Furniture`. This is to say that everything that is true for all `Furniture` is also true for all `Tables`.  Everything is a subsort of the sort `Universe`. This allows one to build really powerful, object-oriented-like hiearchies. But I'm not sure how to translate this object-oriented idea into types. The original implementation just decorated everything with unique strings. But I think we can do better than that with DDLog's type system. Any advice?

Thanks!

**Comment by mbudiu-vmw** [comment]
There is no subtyping in DDlog.
The only thing I can think of is adding the supertypes as members.
You can also look at Souffle, it has some generic types and type hierarchies (called components):
https://souffle-lang.github.io/components
We have an (imperfect) compiler from Souffle into DDlog (tools/souffle_converter.py).

**Comment by d4hines** [comment]
Ok, cool, I'll check it out.

One thing that comes to mind is to just generate duplicate code all the way up the hierarchy. For example, any rules that I write for `Furniture` would be duplicated for every (terminal) subtype of `Furniture`. It would be bulky, but I think it would work...

**Comment by mbudiu-vmw** [comment]
That's roughly how we compile the Components in Souffle.

**Comment by ryzhyk** [comment]
@d4hines, your approach makes sense. There might be other ways to do it, including some creative use of variant types to model multiple derived classes.  Again, an example program showing some typical situations would help.

**Comment by ryzhyk** [comment]
Closing. I think the answer is that we don't support this in DDlog.
