### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by d4hines** [vmware/differential-datalog#640]
Hello!

I'd like to start the conversation of building on Windows. WSL is fantastic, and I recommend WSL as the primary build tool for generating the Rust lib on Windows; however, my use case requires compiling to native Windows binaries, so WSL won't work for compiling the lib.

Fortunately, you're not too far off. I was able to successfully compile and run a DDLog lib by deleting a few things from my (local, autogenerated) template. I'll make a PR with those changes so you can see them, and we can discuss what's need for an actual, working PR.

**Comment by ryzhyk** [comment]
Implemented in #645.
