### ISSUE TITLE
OVSDB bindings can omit deletes and DeltaMinus tables when "isRoot": false

### ISSUE THREAD

**Issue by blp** [vmware/differential-datalog#655]
OVSDB has a "garbage collection" mechanism: in tables that have `"isRoot": false`, ovsdb-server automatically deletes rows that don't have any references from other rows. Currently, the OVSDB bindings for DDlog still send "delete" operations for these tables. These can be omitted, as (I think) the whole DeltaMinus table.

In addition to reducing memory and time, doing this will increase reliability because it eliminates the possibility of DDlog trying to delete a row that still has references. (This came up because I was seeing transaction errors for this reason while debugging.)

**Comment by ryzhyk** [comment]
Thanks, this is a good idea. So the plan is to disable `DeltaMinus` table generation for non-root tables.

I also ran into this type of error. Interestingly, I had not seen them before we switched to using explicit UUIDs. I am not sure I agree with the reliability argument though.  In the examples I've seen, this error indicates a real bug in DDlog code. Removing DeltaMinus will eliminate this particular failure, but it may still manifest, potentially in a more subtle way, later on.

**Comment by blp** [comment]
> Removing DeltaMinus will eliminate this particular failure, but it may still manifest, potentially in a more subtle way, later on.

It shows up differently.

My experience is that the resulting transaction failures have two fairly bad kinds of consequences. First, they get retried frequently (always failing), wasting CPU on the daemon and the database server. Second, since the entire transaction fails it becomes impossible for any kind of update to happen, even one unrelated to the reason that it's failing.

If DeltaMinus is removed, you can end up with "extra" records hanging around, but you don't get the other two problems. It makes the problem less obvious, since the user doesn't see complete breakage, and of course subtle problems are still problems but the system still mostly works.

It's a trade-off.

**Comment by ryzhyk** [comment]
Agreed.
