### ISSUE TITLE
Any doc on what "transformer" is?

### ISSUE THREAD

**Issue by Escapingbug** [vmware/differential-datalog#692]
I found the keyword "transformer" reserved and used as "extern transformer" within library function (especially "graph.dl") but found no useful reference what it is and how it should be used.

Do we have any resource on this? Or anyone can explain a little bit on how this is plan to be implemented (I saw that only "extern transformer" is possible for now) in the end, and how external ones can be used for now?

**Comment by ryzhyk** [comment]
Transformers are a way to invoke incremental computations implemented in Rust directly on top of differential dataflow.  This is useful for those computations that cannot be expressed in DDlog, but can be implemented in differential.  A transformer takes one or more relations and returns one or more relations.  You are right, only `extern` transformers are supported at the moment. Non-extern transformers, i.e. transformers implemented in DDlog, may be introduced in the future as a form of code reuse (a transformer can be used to create a computation that can be instantiated multiple times for different input/output relations).

**Comment by ryzhyk** [comment]
Hopefully #694 addresses this.  @Escapingbug , feel free to re-open if you feel this should be clarified further.
