### ISSUE TITLE
DDlog Java API binding error

### ISSUE THREAD

**Issue by sdifv** [vmware/differential-datalog#721]
Hello, when I  followed the [instruction](https://github.com/vmware/differential-datalog/blob/master/doc/java_api.md) to  bind my program to ddlog Java API, I encountered the following error:   
```bash
$ cc -shared -fPIC -I${JAVA_HOME}/include -I${JAVA_HOME}/include/${JDK_OS} -I. -I${DDLOG}/lib ${DDLOG}/java/ddlogapi.c -Ltarget/release/ -lrouting_ddlog -o libddlogapi.so
/home/yhhuang/differential-datalog/java/ddlogapi.c: In function ‘Java_ddlogapi_DDlogAPI_ddlog_1run’:
/home/yhhuang/differential-datalog/java/ddlogapi.c:199:25: error: too few arguments to function ‘ddlog_run’
         handle = (jlong)ddlog_run((unsigned)workers, storeData, NULL, 0, eprintln);
                         ^~~~~~~~~
In file included from /home/yhhuang/differential-datalog/java/ddlogapi.c:14:0:
./ddlog.h:193:19: note: declared here
 extern ddlog_prog ddlog_run(
                   ^~~~~~~~~
/home/yhhuang/differential-datalog/java/ddlogapi.c:217:21: error: too few arguments to function ‘ddlog_run’
     handle = (jlong)ddlog_run((unsigned)workers, storeData, commit_callback, (uintptr_t)cbinfo, eprintln);
                     ^~~~~~~~~
In file included from /home/yhhuang/differential-datalog/java/ddlogapi.c:14:0:
./ddlog.h:193:19: note: declared here
 extern ddlog_prog ddlog_run(
                   ^~~~~~~~~
```
The differential-datalog version is 0.19.0,  if just compiling the excecutable cli program, it can work successfully.
 
I guess it may be that the version of the dependent code file is not adapted, resulting in an error in the function call. How can I deal with this problem? Thanks!

**Comment by ryzhyk** [comment]
Hi! Looks like you pulled the latest DDlog repo, but did not re-build your DDlog project with it. Try running `stack install` in the `differential-datalog` directory and then re-run `ddlog -i` on your `.dl` file.  This should update your generated Rust project, including creating a new `ddlog.h` that should be compatible with `ddlogapi.c`.

**Comment by sdifv** [comment]
Thank you very much for your answers, Now the problem is solved!
