### ISSUE TITLE
FlatMap doesn't seem to work with a collection of tuples.

### ISSUE THREAD

**Issue by dhaya** [vmware/differential-datalog#722]
Hello,
I am not able to get FlatMap working with a vector of tuples. Here is a minimal datalog file which is a rather silly extension of the tutorial example which just adds a count of 1 to each returned string from split. 
 
```

function split_ip_list(x: string): Vec<(string, u64)> = {
   var v: Vec<string> = split(x, " ");
   var out: Vec<(string, u64)> = vec_empty();
   for (s in v) {
       vec_push(out, (s,1))
   };
   out
}

input relation HostAddress(host: bit<64>, addrs: string)
output relation HostIP(host: bit<64>, addr: string, count: u64)

HostIP(host, addr, count) :- HostAddress(host, addrs),
                    (var addr, var count) = FlatMap(split_ip_list(addrs)).


```

I get the following error:
**ddlog: Failed to parse input file: "test.dl" (line 14, column 52):
unexpected reserved word "FlatMap"
expecting expression term**

DDlog version used: 
DDlog v0.25.2 (1ec84202eaa30cc5ac95a565e777bd03a79f8e23)

It is likely I am not doing this right. Please let me know if there is another way to do this.

**Comment by ryzhyk** [comment]
What you wrote makes perfect sense and we should support this, but right now DDlog only allows a single variable declaration in the left-hand side of `FlatMap` and `Aggregate` clauses, so you probably want to re-write your rule like this:

```
HostIP(host, addr, count) :- HostAddress(host, addrs),
                    var addr_count = FlatMap(split_ip_list(addrs)),
                    (var addr, var count) = addr_count.
```

or like this

```
HostIP(host, addr_count.0, addr_count.1) :- HostAddress(host, addrs),
                    var addr_count = FlatMap(split_ip_list(addrs)).
```

**Comment by dhaya** [comment]
That works. I appreciate the quick response. Thanks.
