### ISSUE TITLE
Make libddlogapi.so name configurable.

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#726]
We have users who run multiple Java programs that load different DDlog programs. They would like to give their compiled .so files different names.  To support it, we need to extend the DDlog API with optional library name argument (we can keep `libddlogapi.so` as the default).

**Comment by mbudiu-vmw** [comment]
But still every java program will have a single ddlog program?
The ddlog_run method has no way of specifying anything.

**Comment by ryzhyk** [comment]
> But still every java program will have a single ddlog program?

Yes.
