### ISSUE TITLE
[Enhancement] Prebuilt windows binaries

### ISSUE THREAD

**Issue by Kixiron** [vmware/differential-datalog#730]
Prebuild windows binaries would be really amazing, as it's miles easier than building from source

**Comment by ryzhyk** [comment]
We use Travis to create binary releases.  Travis supports Windows, and we did test Windows builds in the past, so this should not be too difficult.

**Comment by Kixiron** [comment]
Do you happen to know the last commit when windows builds worked, I'm trying to bisect so I can get them working again

**Comment by ryzhyk** [comment]
Do you mean native windows or WSL-based build?

**Comment by Kixiron** [comment]
Native windows, preferably

**Comment by ryzhyk** [comment]
@d4hines , do I remember correctly that you reported successful attempt to build DDlog on Windows? If so, do you remember what version you were using?

**Comment by d4hines** [comment]
I don't think I ever tried building it from source on Windows. My workflow was to generate the Rust code using WSL, and then build the Rust code on Windows. The Rust generated by v0.17.4 compiles fine on Windows.

**Comment by ryzhyk** [comment]
Thanks @d4hines!

@Kixiron, apologies about giving you misleading info.  This means that compiling on Windows is going to be a bigger project than I initially thought.

**Comment by ryzhyk** [comment]
Pre-built binaries introduced in v0.31.0.
