### ISSUE TITLE
Support array types and array_agg in SQL frontend

### ISSUE THREAD

**Issue by lalithsuresh** [vmware/differential-datalog#732]
I've been adapting some SQL schemas in DCM to work with ddlog. The latest hurdle is support for SQL's array_agg(), which is an aggregate function that simply takes a column and outputs an array with every entry of that column.

Here are two test DDL statements to work with:

`create table t1(column1 integer, column2 integer, column3 array)`

`create view v1 as select column1, array_agg(column2) from t1 group by column1`

 Another question would be how to query membership within an array type. For example:

`select * from t1 where column1 in unnest(column3)` // seems like standard SQL that H2 also supports

Or...

`select * from t1 where array_contains(column3, column1)` // a non-standard function H2 provides

**Comment by mbudiu-vmw** [comment]
does presto support this?

**Comment by lalithsuresh** [comment]
Yes: https://prestodb.io/docs/current/functions/aggregate.html#array_agg

**Comment by mbudiu-vmw** [comment]
Don't you have to specify the type of the elements of the array? The examples I found on the net seem to do that.
Do you want to create a bunch of unit tests with some queries that you'd like to be supported?

**Comment by mbudiu-vmw** [comment]
Presto cannot parse this: `select * from t1 where column1 in unnest(column3)`

**Comment by lalithsuresh** [comment]
@mbudiu-vmw can you try `select * from t1 where column1 in (unnest(column3))`? `unnest` transforms an array into a relation, so the extra braces might be required to signal that that it's a sub-query.

**Comment by mbudiu-vmw** [comment]
`create view v0 as select distinct column1 from a where column3 in (unnest(column1))`
gives:
`com.facebook.presto.sql.parser.ParsingException: line 1:64: mismatched input 'in'. Expecting: 'AND', 'EXCEPT', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OR', 'ORDER', 'UNION', <EOF>`

Can you give me a query that compiles?

**Comment by lalithsuresh** [comment]
Seems like this is Presto-specific, because that query works in H2. I'll dig a bit and get back to you.

**Comment by lalithsuresh** [comment]
It seems like Presto doesn't allow searching within an array using unnest, judging by the antlr here: https://github.com/prestodb/presto/blob/91b058e83f22776ca701c501269c015611248831/presto-parser/src/main/antlr4/com/facebook/presto/sql/parser/SqlBase.g4
(it treats UNNEST() as a relation, whereas the IN predicate expects either a list or a query afterwards). 

The Presto-way to check for membership in an array is to use contains(array, x): https://prestodb.io/docs/current/functions/array.html, which I think you already implemented?

**Comment by mbudiu-vmw** [comment]
I have implemented array_contains.
