### ISSUE TITLE
Allow refering to enumerations by their parent

### ISSUE THREAD

**Issue by Kixiron** [vmware/differential-datalog#738]
I've encountered a lot of situations where I wanted to write code like this
```prolog
typedef Thing = Thing { .. }

typedef OneOfManyThings = Thing | OtherThing
```
but I can't since each variant becomes a constructor of its own that conflicts. Being able to do something like this would be amazing
```prolog
typedef Thing = Thing { .. }

typedef OneOfManyThings = Thing | OtherThing

var some_value = OneOfManyThings::Thing {}
```

**Comment by Kixiron** [comment]
This can also happen with relations (albeit more purposeful there), e.g.

```prolog
typedef Thing = Thing { .. }

relation Thing(a, b, c)
```

**Comment by ryzhyk** [comment]
You can do this with relations using `[]` syntax:

```
typedef Thing = Thing { a: T1, b: T2 }

relation Thing[Thing]
```

However you can also just write

```
relation Thing(a: T1, b: T2)
```

which expands to the above and will actually create a typedef declaration for `Thing`.  You can then use `Thing` like any normal type, e.g., declare variables of type `Thing`, pass it to functions, etc. Here is a tutorial section on this: https://github.com/vmware/differential-datalog/blob/master/doc/tutorial/tutorial.md#explicit-relation-types

**Comment by ryzhyk** [comment]
> I've encountered a lot of situations where I wanted to write code like this
> 
> ```prolog
> typedef Thing = Thing { .. }
> 
> typedef OneOfManyThings = Thing | OtherThing
> ```

I can see how this is appealing, but I actually think this syntax is problematic. In particular, neither Rust nor Haskell (the two languages that inspired DDlog's type system) allow this. Basically, types and constructors are different constructs and cannot be used interchangeably. The standard workaround is:

```
typedef Thing = Thing { .. }

typedef OneOfManyThings = OptionThing{t: Thing} | OptionOtherThing {o: OtherThing}
```

**Comment by ryzhyk** [comment]
PS. If you know of a language that supports this construct in a statically typed fashion, I'd be interested to know about it!

**Comment by mbudiu-vmw** [comment]
Seems somewhat related to union types in TypeScript: https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

**Comment by Kixiron** [comment]
I may be misunderstanding, but it seems to me like Rust supports at least a version of this
```rust
struct Thing { .. }

enum MaybeThing {
    Thing(Thing),
    None,
}
```

**Comment by ryzhyk** [comment]
> I may be misunderstanding, but it seems to me like Rust supports at least a version of this
> 
> ```rust
> struct Thing { .. }
> 
> enum MaybeThing {
>     Thing(Thing),
>     None,
> }
> ```

I think this is just a constructor that happens to have the same name as a type plus this enum uses tuple struct syntax, which allows anonymous fields, but if you were to match it in Rust, you'd still do something like:

```
match x {
    MaybeThing::Thing(Thing{...}) => ...,
   ...
}
```

**Comment by Kixiron** [comment]
Yes, that's kinda what I'm shooting for, the ability to have similarly-named items within the same scope

**Comment by ryzhyk** [comment]
I see. Well, we can do:

```
typedef Thing1 = T1 {x: bool}
typedef Thing2 = T2 { y: bool}

typedef OneOf = Thing1{t1: Thing1} | Thing2{t2: Thing2}
```

but this isn't very helpful tbh.

The reason Rust allows this is because enum constructors are by default scoped within the enum name, e.g., `MaybeThing::Thing`, which avoids name clashes. DDlog, otoh, takes the Haskell path here, where constructors, like functions, have globally visible names.  I agree that the Rust way is probably nicer, but I don't think we'll be changing this in the current version of DDlog.

**Comment by ryzhyk** [comment]
> Seems somewhat related to union types in TypeScript: https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

Interesting.  It does not seem type-safe though, e.g., here is one of the examples:
```
  switch (state.state) {
    case "loading":
      return "Downloading...";
    case "failed":
      // The type must be NetworkFailedState here,
      // so accessing the `code` field is safe
      return `Error ${state.code} downloading`;
    case "success":
      return `Downloaded ${state.response.title} - ${state.response.summary}`;
  }
```

**Comment by mbudiu-vmw** [comment]
In general TypeScript is not typesafe, since it includes javascript, but it has a type-safe subset which is very nice.

**Comment by ryzhyk** [comment]
@Kixiron , are you ok with me closing this?

**Comment by Kixiron** [comment]
Yah, that's alright
