### ISSUE TITLE
Workspace breaks pre-workspaced environments

### ISSUE THREAD

**Issue by Kixiron** [vmware/differential-datalog#741]
I'm trying to integrate DDlog into a preexisting library, but since the generated Cargo.toml includes a workspace I'm faced with an error

```
error: multiple workspace roots found in the same workspace:
  ~\crunch-lang\crates\crunch-typecheck\typecheck_ddlog
  ~\crunch-lang
```

There's no real way to rectify this for me right now, I just have to edit the generated file to remove said workspace every time I rebuild ddlog
Being able to toggle the workspace would be wonderful for situations like this, then library users could simply disable it while others are unaffected

**Comment by Kixiron** [comment]
The `[profile]` section also causes Cargo to emit warnings when the workspace is disabled, so that could also not be emitted when the workspace is toggled off

```
package:   ~\crunch-lang\crates\crunch-typecheck\typecheck_ddlog\Cargo.toml
workspace: ~\crunch-lang\Cargo.toml
```

**Comment by ryzhyk** [comment]
Is there a reason you want to include DDlog-generated crates in your workspace as opposed to using them as dependencies? Or does that cause Rust to complain?

In one of our projects our build script symlinks our other Rust crates under the same workspace and modifies `Cargo.toml` to include these crates in the workspace, which is less than ideal.  Sounds like you took a slightly different path, which also works.

Overall, our Rust API is both really ugly and undocumented, which is ironic, as it is DDlog's native interface.  We should at least add an example illustrating how to use the API, but also start working on improving it, which will involve generating some convenience wrappers around DDlog-generated types.

**Comment by Kixiron** [comment]
That's the thing, I am using it as a dependency but it just happens to sit within my workspace (which is my entire repo). As of now I have a structure like this
```
my-workspace/
    crate-that-uses-ddlog/
        src/
            ..my code
        ddlog-generated-code/
            ...generated code
    ...other crates
```
So the generated workspace is used as a dependency of `crate-that-uses-ddlog`, which causes Cargo to error out on nested workspaces

**Comment by Kixiron** [comment]
And as an idea, I think a proc-macro for `#[derive(ToRecord)]` and `#[derive(FromRecord)]` would be absolutely amazing in terms of ergonomics. Additionally if y'all feel like the library is stable enough/it's the path you want to take, then separating more parts of the generated code out into crates.io-served crates would be really cool, it'd help compilation times, shared resources and also work to give a stable interface around the inherently unstable generated code

**Comment by ryzhyk** [comment]
> That's the thing, I am using it as a dependency but it just happens to sit within my workspace (which is my entire repo). As of now I have a structure like this
> 
> ```
> my-workspace/
>     crate-that-uses-ddlog/
>         src/
>             ..my code
>         ddlog-generated-code/
>             ...generated code
>     ...other crates
> ```
> 
> So the generated workspace is used as a dependency of `crate-that-uses-ddlog`, which causes Cargo to error out on nested workspaces

Does the error go away if the generated code does not live under the same directory?

**Comment by Kixiron** [comment]
If the generated code's not within the workspace yes, but the workspace for the generated code shouldn't really be need in of itself

**Comment by ryzhyk** [comment]
> And as an idea, I think a proc-macro for `#[derive(ToRecord)]` and `#[derive(FromRecord)]` would be absolutely amazing in terms of ergonomics (If records are supposed to be the primary interface, which I'm not entirely sure of since I'm just experimenting).

That's an interesting suggestion.  Records are the primary interface if you are passing dynamically typed data to DDlog.  If the set of types you're passing is static and known in advance, then you should use the type safe and more efficient interface, which basically allows passing DDlog-generated types between your program and DDlog. These types are part of the the generated `types` and `value` crates. I will try to come up with an example within the next few days.

**Comment by ryzhyk** [comment]
> Additionally if y'all feel like the library is stable enough/it's the path you want to take, then separating more parts of the generated code out into crates.io-served crates would be really cool, it'd help compilation times, shared resources and also work to give a stable interface around the inherently unstable generated code.

This is definitely a good idea, but I'm worried about the much more complex release management process. It's so much easier to package the whole thing in one archive than uploading multiple releases of individual crates.

**Comment by Kixiron** [comment]
That's definitely true, multi-crate releases can be a nightmare, but [`cargo-release`](https://github.com/sunng87/cargo-release) can help things if y'all ever look into that path
