### ISSUE TITLE
error parsing variable name starting with "not"

### ISSUE THREAD

**Issue by bharaniabhishek123** [vmware/differential-datalog#746]
I am having a variable named 
var notbefore = current_date()

function current_date(): Date = {
    unwrap_or_default(date_parse("08/21/2020", "%m/%d/%Y"))
}

When I am using this variable in if statement it throws error : 
 Unknown variable: notbefore

**Comment by mbudiu-vmw** [comment]
Indeed, this is a bug with the parser which parses "not" as follows:
```
etable = [[postf $ choice [postTry, postSlice, postApply, postField, postType, postAs, postTupField]]
         ,[pref  $ choice [prefixOp "not" Not]]
```

This does not require a space between "not" and the following identifier. In consequence the expression "notable" is parsed as "not able". Here is a reproduction:

```
function p(): string {
    var notable = "hi";
    notable
}
```

I will try to figure out how to force prefixOp require a space.

**Comment by mbudiu-vmw** [comment]
I wonder whether a similar problem could happen for binary operators "and" and "or".
