### ISSUE TITLE
name mangling for extern functions in submodules breaks

### ISSUE THREAD

**Issue by eqv** [vmware/differential-datalog#762]
I have a module some_mod.dl
```c
extern function foo(): string

function bar() : string {
    foo()
}
```
and an implementation of the extern function in some_mod.rs:

```rust
fn foo() -> String{
    return "foo".into();
}
```

when importing the module, the code breaks:

```bash
error[E0425]: cannot find function `some_mod_foo` in this scope
    --> types/lib.rs:2229:51
     |
2229 |   lazy_static!{ pub static ref __STATIC_0: String = some_mod_foo() ; }
     |                                                     ^^^^^^^^^^^^ help: a function with a similar name exists: `some_mod_bar`
...
2372 | / pub fn some_mod_bar() -> String
2373 | | {   (*(&*__STATIC_0)).clone()
2374 | | }
     | |_- similarly named function `some_mod_bar` defined here
```

types.rs contains the definition of foo as:

```rust
pub use __some_mod::*;
mod __some_mod {
    use super::*;
    fn foo() -> String{
        return "foo".into();
    }
}

```
however the function is called as 
```
lazy_static!{ pub static ref __STATIC_0: String = some_mod_foo() ; }
```

I think the name mangling for sub modules is only partially applied. While we are at that. Why is the sub module name prefixed to each enum variant defined in that module? To ensure nothing collides with `use Enum::*` in the scope of types/src/lib.rs?

**Comment by eqv** [comment]
Note that this is not due to the fact that foo() is a constant function, and stored in a static value. It also occurs with more complex functions, I just tried to create a minimal test case.

**Comment by ryzhyk** [comment]
This is how name mangling works in the current version: type and function names in modules (except the top-level module) must be prefixed with module name (in your case, `same_mod_foo`).  In case of extern functions, you must do the mangling yourself, the compiler will not rename extern functions for you.

However, if you switch to PR #763, it does away with name mangling. It relies on the Rust module structure for namespace isolation, compiling each DDlog module into a separate Rust module, so your code should work.  Here is some documentation on this: https://github.com/ddlog-dev/differential-datalog/blob/modules_scoped/doc/tutorial/tutorial.md#implementing-extern-functions-and-types-in-rust

> While we are at that. Why is the sub module name prefixed to each enum variant defined in that module? To ensure nothing collides with use Enum::* in the scope of types/src/lib.rs?

This is for no good reason; and we also do away with this behavior in #763.

**Comment by eqv** [comment]
Cool, good to know!

**Comment by eqv** [comment]
It seems like just explicitly renaming the rust function works only if it is declared but not used within the module (and than used in another module).  If the function is called in the module itself, it's still not found. But this will probably also go away with #763.

**Comment by ryzhyk** [comment]
Umm, never seen that before. What do the DDlog and Rust declarations look like and what is the error message?  Is it possible that another function with the same name exists in the module (overloading does not work for extern functions)?

**Comment by eqv** [comment]
pretty much the example from above, but with some_mod_ prefixed in various configuration yielding various errors. I couldn't get it to work. I don't think it matters though - if it's still a problem after #763, I'll reopen this issue.
