### ISSUE TITLE
Recursive Types with typedef

### ISSUE THREAD

**Issue by eqv** [vmware/differential-datalog#767]
This works as expected:
```
typedef ExprT = NegT{op: Ref<ExprT>}
```
However 
```
typedef Expr = Ref<ExprS>
typedef ExprS = NegS{op: Expr}
```
Fails with 
```
ddlog: error: bse.dl:3:1-4:1: Recursive alias types: Expr -> ExprS -> Expr
typedef Expr = Ref<ExprS>
```

Is this intended behavior?

**Comment by ryzhyk** [comment]
Yes, it's intended, basically because Rust refuses to compile the resulting recursive type declaration, at least in some cases.

**Comment by eqv** [comment]
Is there any way to get a transparent typedef that just introduces an alias?

**Comment by ryzhyk** [comment]
Yes, just not a recursive one, e.g.,:

```
typedef int_t = u64
typedef OptionalString = Option<string>
typedef OptionalRef<'T> = Option<Ref<'T>>
```

**Comment by eqv** [comment]
dang, thanks
