### ISSUE TITLE
Parser reports unknown function when it's an unknown overload

### ISSUE THREAD

**Issue by blp** [vmware/differential-datalog#768]
This is surprising at first. Example:

```
$ cat foo.dl
function a(x: bit<16>, y: bit<16>): bit<16> { x + y }
function b() { a(0) }
$ ddlog -i foo.dl -L ~/differential-datalog/lib/
ddlog: error: foo.dl:2:16-2:21: Unknown function 'a'
function b() { a(0) }
               ^^^^^
```

**Comment by mbudiu-vmw** [comment]
I guess the error message is not very good.

**Comment by ryzhyk** [comment]
It should specify explicit missing function signature and also list functions with the same name that do not satisfy this signature.

**Comment by ryzhyk** [comment]
Thanks for the repro, @blp , I fixed this as part of an upcoming PR that implements closures, and added your example to the test suite.
