### ISSUE TITLE
Two new souffle test failures.

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#773]
I did not look closely into this, but it appears that Souffle has a new operator we don't support, used in the following tests: multiple_inequalities, rangeop.

**Comment by mbudiu-vmw** [comment]
They added a "range" operator, which generates a set of values. I wonder why they did that, this is fully expressible in datalog. Maybe having an operator is more efficient? The typing is also very weird:
`out1(X) :- X = range(1, 10)`. X is a scalar between 1 and 9 inclusive.
