### ISSUE TITLE
[Feature Request] Renaming indexes and relations

### ISSUE THREAD

**Issue by Kixiron** [vmware/differential-datalog#814]
On projects broken up into modules, indexes and relations will often have names like `foo_bar_baz_IndexName`, an attribute to set the in-rust name would be really nice

```prolog
// module foo::bar::baz

#[index_name = "IndexName"]
index IndexName() on SomethingToIndex()
```

**Comment by ryzhyk** [comment]
As we evolve the implementation of DDlog to have the Rust module/crate hierarchy mirror the DDlog project tree, index and relation names will eventually become properly scoped: `foo::bar::baz::IndexName`. One day we might even improve the module system with proper namespace management features (hiding, re-exports, etc., as discussed in the other issue), which will enable shortcuts like `IndexName` in your example in both DDlog and Rust code. As always, I prefer to wait for a proper fix to adding more workarounds, even if it takes longer.

**Comment by Kixiron** [comment]
I'm definitely all for a more complete module system, that'd be amazing
