### ISSUE TITLE
How to fix Arch Linux gmp build error with 0.31.0

### ISSUE THREAD

**Issue by jicksta** [vmware/differential-datalog#818]
Took my a while to figure out why ddlog was failing to compile on Arch Linux. I've reproduced the build error with the following simple Dockerfile:

```
FROM archlinux
RUN pacman -Sy --noconfirm base-devel stack git
RUN git clone --depth=1 https://github.com/vmware/differential-datalog.git /ddlog
WORKDIR /ddlog
RUN stack build
```

This results in the following compile error ([full docker build log](https://gist.githubusercontent.com/jicksta/5d09716345468daff608392dbcc16dbb/raw/2570d674bcc61e492bb80ce4bedc35f33ff3d594/gistfile1.txt)):

```
...
integer_gmp_mpn_ior_n: error: undefined reference to '__gmpn_ior_n'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
Completed 37 action(s).

--  While building package differential-datalog-0.17.0.0 (scroll up to its section to see the error) using:
      /root/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:differential-datalog exe:ddlog exe:debugparser exe:ovsdb2ddlog --ghc-options ""
    Process exited with code: ExitFailure 1
The command '/bin/sh -c stack build' returned a non-zero code: 1
```

After working on a few other workarounds, I found that the simplest solution for this, which I'm including here for posterity, is `yay -S libgmp-static` from the AUR. (Note: `gmp` itself comes from `base-devel`)

I can't figure out whether the gmp-related build issue has something to do with ddlog or something else upstream... I'm guessing it's an upstream issue, probably from the Arch Linux folks.

**Comment by jicksta** [comment]
Closing the ticket since I just wanted to share the fix for anyone else who might encounter this.

**Comment by ryzhyk** [comment]
@jicksta , thanks for reporting the problem _and_ the fix. Haskell-generated programs require `libgmp`. The readme does mention this, but does not have Arch-specific instructions.  I will add your solution to the README.

**Comment by ryzhyk** [comment]
@jicksta , what's the equivalent of   `apt install libc6-dev libgmp-dev` on Arch Linux, i.e., a command (or commands) to install both libraries?

**Comment by jicksta** [comment]
@ryzhyk AFAIK, the `gmp` package that's bundled with `base-devel` in the mainline package repo should include everything for linking and compilation:

```
% pacman -Q --list gmp
gmp /usr/
gmp /usr/include/
gmp /usr/include/gmp.h
gmp /usr/include/gmpxx.h
gmp /usr/lib/
gmp /usr/lib/libgmp.so
gmp /usr/lib/libgmp.so.10
gmp /usr/lib/libgmp.so.10.4.0
gmp /usr/lib/libgmpxx.so
gmp /usr/lib/libgmpxx.so.4
gmp /usr/lib/libgmpxx.so.4.6.0
gmp /usr/lib/pkgconfig/
gmp /usr/lib/pkgconfig/gmp.pc
gmp /usr/lib/pkgconfig/gmpxx.pc
gmp /usr/share/
gmp /usr/share/info/
gmp /usr/share/info/gmp.info-1.gz
gmp /usr/share/info/gmp.info-2.gz
gmp /usr/share/info/gmp.info.gz
```
The `libgmp-static` package I mentioned above is from the Arch User Repository ([AUR](https://aur.archlinux.org/packages/libgmp-static/)), a `pacman` repo for user-contributed packages not officially blessed by the Arch maintainers. It apparently contains only a single file, an archive library:

```
% yay -Q --list libgmp-static
libgmp-static /usr/
libgmp-static /usr/lib/
libgmp-static /usr/lib/libgmp.a
```

It's a bit outside my wheelhouse to diagnose where the real issue here since I have only a superficial understanding of the Haskell ecosystem at the moment. 

For Arch Users, perhaps the best option in the end would be to create a PKGBUILD for ddlog so that it can be installed by any Arch user with a simple `yay -S ddlog`; this could include an automatic dependency on the AUR `libgmp-static` package, as well as `stack`, etc. It's a little weird on Arch because the `stack` and `ghc` packages don't share their compilers with each other, therefore when `stack` is building a program like ddlog with its own compiler, I suspect the `stack`-built `ghc` may be getting confused by system libraries installed outside its prefix deep in a `.stack` hidden dir somewhere. I use `XMonad`, so I need to have the system `ghc` package installed since I recompile my Haskell-based window manager almost daily.

Is there any way for the ddlog build scripts to play nicely with the gmp shared libraries instead of statically linking `libgmp`?

**Comment by ryzhyk** [comment]
@jicksta , thanks for the clarification!

DDlog could be built without dynamic version of gmp by removing `optl-static` from `package.yaml`, but then the resulting binary wouldn't be self-contained and would require users to install `libgmp`.  In contrast, if you download a DDlog binary release, it should just work on any Linux system.  Likewise, if someone with Arch Linux expertise wanted to create a DDlog package for Arch Linux, that package wouldn't need to depend on `libgmp` as it is already linked into the DDlog executable.

Did you also have to install a static version of GNU libc?  On Ubuntu the required package is `libc6-dev`.  Do you know what package we need on Arch Linux?
