### ISSUE TITLE
Performance of multiple workers

### ISSUE THREAD

**Issue by yueshangzuo** [vmware/differential-datalog#820]
Hello,

I run some tests with multiple workers, but the program is slower than with a single worker. I read some parts of the translated Rust program, and in my view, the `arrange/shuffle` operation of each operator which passes messages among workers may be a reason. Is that correct? Also, does the project D3log aim to solve this problem? 

I don't know if I should discuss the multiple-workers problem in here or in DD/TD, it's just a little weird for me that the Datalog program does not scale well with a parallel framework as the underlying system. Any help will be sincerely appreciated!

**Comment by ryzhyk** [comment]
@yueshangzuo, the scalability of both DD and DDlog is a function of the program and the dataset. Your observation is consistent with our experience:  DDlog usually does not scale beyond two threads, and even going from one to two may or may not improve the performance depending on the benchmark.  You are also correct that the main bottleneck is worker-to-worker synchronization, which happens after every operator in the dataflow graph.  We also observed that DD often scales better than DDlog running a similar benchmark, which means that something in the way we encode DDlog programs into DD is suboptimal from the scalability perspective.  This is one of the open problems that we haven't had the resource to investigate yet.  The solution will likely involve improvements to both DDlog and DD.

> Also, does the project D3log aim to solve this problem?

Yes. This is not the primary purpose of D3log, but it does have the potential to improve scalability by implementing a different way to parallelize the execution.

**Comment by ryzhyk** [comment]
PS. DD recently implemented a new worker-to-worked communication mechanism based on crossbeam.  This seems to have improved DD's scalability on some benchmarks.  We are not yet using that version of DD, which might also contribute to different multicore scaling behavior.

**Comment by yueshangzuo** [comment]
Thanks for your reply! I'll look into the crossbeam channels.
