### ISSUE TITLE
(Question) Turing complete, or incomplete?

### ISSUE THREAD

**Issue by AndrewBrownK** [vmware/differential-datalog#824]
Is DDlog turing complete, or incomplete?

For any valid DDlog program, if I supply some input relations, am I guaranteed the engine will finish processing a complete but finite quantity of output relations?

If the answer is no, then what patterns and pitfalls enable this? 

In my own use case, I want to avoid infinite or non-terminating output deltas.

**Comment by ryzhyk** [comment]
There are several ways to write a non-terminating DDlog program:

1. Using relations with infinite domains, e.g.,:

```
output relation AllIntegers(n: bigint)

// Enumerate all integers starting from 0.
AllIntegers(0).
AllIntegers(n+1) :- AllIntegers(n).
```

2. By combining recursion with aggregation. DDlog supports arbitrary user-defined aggregates and will happily apply them inside a recursive fragment of the program. This can be very useful in practice, but may not terminate if the aggregate is non-monotonic. Basically, we rely on the user to ensure convergence.

```
output relation R1(n: usize)

R1(5).
R1(m) :-
    R1(n),
    // this will cause the program to fluctuate adding and removing 0 from `R1` forever.
    var m = n.group_by(()).custom_aggregate().

function custom_aggregate(g: Group<(), usize>): usize {
    if (g.first() == 5) {
        0
    } else {
        5
    }
}
```

3. Using loops or recursive functions. DDlog's expression language is basically a general-purpose programming languages and is itself Turing complete, e.g., one can easily implement infinite recursion in it. Infinite loops are not possible right now, as one can only iterate over a collection, but other types of loops may be added in the future.

All of the above capabilities make DDlog more expressive both in theory and in practice, but do so at the cost of potential non-termination.

**Comment by AndrewBrownK** [comment]
Thanks for the useful info!
