### ISSUE TITLE
DDlogRecord api: how to do updates?

### ISSUE THREAD

**Issue by lalithsuresh** [vmware/differential-datalog#831]
I'm trying to implement SQL UPDATE queries in ddlog-jooq. Example query I want to support:

`update hosts set capacity = 11 where id = 'n1'`

... where `id` is a primary key in the hosts table.

What's the right way to pull this off using the DDlogRecord Java API? The only `DDlogCommand.Kind` types I see are `Insert`, `DeleteKey` and `DeleteVal`.

If there is no way to issue an update, I suppose I could do a delete followed by an insert, but that would require me to also maintain an index by primary key on the java side. Right now, I only need to materialize a set of records that are part of each output relation.

**Comment by ryzhyk** [comment]
Hmm, we need to add `InsertOrUpdate` command to the Java API. It has the effect of overwriting existing primary key if any.
@mbudiu-vmw , can you help with this?

**Comment by lalithsuresh** [comment]
You'd also need a way to receive only a subset of (maybe named?) fields to update. Right now, the DDLogCommand accepts an array of DDLogRecords, and the array length has the match the number of fields in the input relation.

**Comment by mbudiu-vmw** [comment]
I am assigned to do it.

**Comment by mbudiu-vmw** [comment]
> You'd also need a way to receive only a subset of (maybe named?) fields to update. Right now, the DDLogCommand is instantiated with an array of DDLogRecords, and the positions in the array correspond to fields in the input relation.

Even for update you still need to supply all the fields.

**Comment by ryzhyk** [comment]
> You'd also need a way to receive only a subset of (maybe named?) fields to update. Right now, the DDLogCommand is instantiated with an array of DDLogRecords, and the positions in the array correspond to fields in the input relation.

Ok, we need to also expose `Modify` for this.  It needs to be added to the C API first (#523).

**Comment by lalithsuresh** [comment]
In that case, I'll need to maintain an index for all input relations myself on the Java side right? So I might as well do a delete + insert then?

**Comment by mbudiu-vmw** [comment]
If there is a Rust API it should not be that difficult. But I thought we had a ModifyOrUpdate

**Comment by ryzhyk** [comment]
To make things more annoying, `Modify` will fail if the key does not exist. This is how `DeleteKey` also behaves.  I wonder if we should change this behavior and just ignore such commands? In any case, with the current behavior you probably want `Modify` to be the sole command in the transaction.

**Comment by ryzhyk** [comment]
> If there is a Rust API it should not be that difficult. But I thought we had a ModifyOrUpdate

There is no `ModifyOrUpdate` (what would it even do?) but yes, `Modify` exists in the Rust API.

**Comment by mbudiu-vmw** [comment]
Sorry, ModifyOrInsert.

**Comment by ryzhyk** [comment]
> > > You'd also need a way to receive only a subset of (maybe named?) fields to update. Right now, the DDLogCommand is instantiated with an array of DDLogRecords, and the positions in the array correspond to fields in the input relation.
> 
> > Even for update you still need to supply all the fields.
> 
> In that case, I'll need to maintain an index for all input relations myself on the Java side right? So I might as well do a delete + insert then?

That's an option, but sounds like `Modify`, which only lets you supply the fields that have changed, is a better option for you (not sure how hard it is to support in the SQL compiler though).

**Comment by mbudiu-vmw** [comment]
We have one other open issue related to primary keys and rollback of failing updates: https://github.com/vmware/differential-datalog/issues/372

**Comment by ryzhyk** [comment]
> Sorry, ModifyOrInsert.

Well, there's `InsertOrUpdate`, which requires supplying all fields of the record.  `Modify` on the other hand requires only supplying fields that have changed, which means that it does not have sufficient information to perform an insert.

**Comment by ryzhyk** [comment]
> We have one other open issue related to primary keys and rollback of failing updates: #372

Yep, and I recently realized that the problem there is worse than what the issue describes.  The behavior is not just undocumented, but is basically broken.

**Comment by lalithsuresh** [comment]
> > > > You'd also need a way to receive only a subset of (maybe named?) fields to update. Right now, the DDLogCommand is instantiated with an array of DDLogRecords, and the positions in the array correspond to fields in the input relation.
> > 
> > 
> > > Even for update you still need to supply all the fields.
> > 
> > 
> > In that case, I'll need to maintain an index for all input relations myself on the Java side right? So I might as well do a delete + insert then?
> 
> That's an option, but sounds like `Modify`, which only lets you supply the fields that have changed, is a better option for you (not sure how hard it is to support in the SQL compiler though).

`Modify` and being able to specify only a subset of fields which have changed would be easier for me in the SQL compiler.

**Comment by mbudiu-vmw** [comment]
We'll start by making sure that the C API has the function, then we'll expose it in Java. 
DDlogRecords are not completely self-describing - they do not contain field names, so we need a way to specify that.

**Comment by mbudiu-vmw** [comment]
What's the Rust API?

**Comment by ryzhyk** [comment]
>  DDlogRecords are not completely self-describing - they do not contain field names, so we need a way to specify that.

In Rust there is a self-describing version.  Did we not expose that in Java?

**Comment by ryzhyk** [comment]
> What's the Rust API?

Check out `rust/template/differential_datalog/record.rs`. It has `ddlog_insert_cmd`, `ddlog_insert_or_update_cmd`, etc. You want to add `ddlog_modify_cmd`.

**Comment by ryzhyk** [comment]
@mbudiu-vmw, was this resolved by #833 or are we waiting for @lalithsuresh to confirm?
