### ISSUE TITLE
Support to encode and decode base64 strings

### ISSUE THREAD

**Issue by klsravani** [vmware/differential-datalog#837]
Need utility methods to perform base64 encoding and decoding for a given string.

**Comment by mbudiu-vmw** [comment]
DDlog makes it easy to interact with libraries written in Rust. You declare a function as "extern" and then you supply a Rust implementation of your function. There are lots of example libraries in the lib directory. In your case you may be able to just expose ddlog function wrappers for functions in this Rust crate: https://docs.rs/base64/0.13.0/base64/. Let us know if you need help writing the wrappers. Also, if you do, please consider contributing them as a new DDlog library.
