### ISSUE TITLE
A way to read messages from Standard Error in Java API

### ISSUE THREAD

**Issue by roymanish** [vmware/differential-datalog#838]
Currently during compilation is something goes wrong it just logs the error in Standard Err and terminates. We should have a mechanism to return these error messages to the caller

**Comment by mbudiu-vmw** [comment]
Do you want to suggest an API for that?

**Comment by roymanish** [comment]
Sorry did not get your question. Are you asking the context in which i have asked this requirement?

**Comment by mbudiu-vmw** [comment]
I assume you are talking about the helper functions in DDlogAPI.java named compileDDlogProgram*. Currently these functions invoke external processes to compile dl programs, and optionally capture stdout and stderr. They also return a boolean on success. We could have them return an object with a boolean field "success" and a pair of strings containing stderr and stdout. Would this be a good API?

**Comment by roymanish** [comment]
Yes this sounds good to me.
