### ISSUE TITLE
Make the types crate re-export all sub-crates

### ISSUE THREAD

**Issue by Kixiron** [vmware/differential-datalog#870]
The generated `types` crate should recreate the module hierarchy and reexport all sub crates

Given a ddlog structure like this
```
main.dl
    module1.dl
    module2.dl
        sub_module.dl
```
The `types` crate should rename and reexport the generated crates to match this
```rust
// types/lib.rs
pub use types__module1 as module1;
pub mod module2 {
    pub use ::types__module2::*;
    pub use types__sub_module as sub_module;
}
```

**Comment by ryzhyk** [comment]
We already do this. Check out the `typedefs` module inside the main crate in the generated rust project.

**Comment by Kixiron** [comment]
I didn't see that, my bad!
