### ISSUE TITLE
"Variable is both declared and used inside relational atom"

### ISSUE THREAD

**Issue by jinyang175** [vmware/differential-datalog#873]
Hi,

When i compile the following datalog program: 

```
input relation LDMH(a:string)
input relation KCJT(a:string, b:string)
relation GAIO(a:string)
output relation TUGD(a:string, b:string)



GAIO(aa) :- KCJT(aa,aa).
TUGD(v,g) :- LDMH(v), LDMH(g), GAIO(g).
```
I get: 

```
ddlog: error: rules.dl:8:18-8:20: Variable "aa" is both declared and used inside relational atom KCJT(.a=aa, .b=aa) at the following locations:
  rules.dl:8:18-8:20
  rules.dl:8:21-8:23
GAIO(aa) :- KCJT(aa,aa).
```

But isn't this allowed? Or am I misunderstanding something?

**Comment by mbudiu-vmw** [comment]
Perhaps the compiler should do this automatically. Can you try to replace KCJT(aa, aa) with KCJT(aa, ab), aa == ab;?

**Comment by ryzhyk** [comment]
This is an unfortunate implementation restriction.  @mbudiu-vmw 's solution is the best workaround for the time being.

**Comment by jinyang175** [comment]
I see. Yes, the workaround works!

Thanks, guys!
