### ISSUE TITLE
[Optimization] Don't concatenate input relations

### ISSUE THREAD

**Issue by Kixiron** [vmware/differential-datalog#928]
If an input relation is only used once within a rule, it still will be concatenated even though there's no other collections to concatenate it with

![image](https://user-images.githubusercontent.com/25047011/109724725-9c622580-7b75-11eb-953b-8d4df7657467.png)
![image](https://user-images.githubusercontent.com/25047011/109724750-a6842400-7b75-11eb-9f89-e2f398b6de1a.png)

**Comment by ryzhyk** [comment]
@Kixiron , did you resolve this in one of your recent PRs?  If not, do you think you could create example programs for this and other similar issues you submitted?  Thanks!

**Comment by Kixiron** [comment]
Yes, I believe that I did manage to fix this one
