### ISSUE TITLE
Better document how to use built-in types in the CLI

### ISSUE THREAD

**Issue by norcalli** [vmware/differential-datalog#939]
It seems as if only types we defined ourselves are able to be used as input in the CLI mode. This seems like an oversight which drastically hinders the utility of the CLI input testing loop.

I was trying to construct a type which contained an Option and I got `unknown constructor None of type Option`.

**Comment by ryzhyk** [comment]
Any types can be used in a .dat file, you just need to use fully qualified constructor names: `ddlog_std::None`, `ddlog_std::Some{..}`

**Comment by norcalli** [comment]
oh... Then I guess this is more of an issue with documentation since I didn't see that in the tutorial or command_reference. I'll change the title

**Comment by ryzhyk** [comment]
Resolved via #941
