### ISSUE TITLE
Orphan link in documentation

### ISSUE THREAD

**Issue by gz** [vmware/differential-datalog#944]
In https://github.com/vmware/differential-datalog/blob/master/doc/command_reference/command_reference.md:
"Extern types implement their own custom update semantics. The programmer defines this semantics by implementing the Mutator trait declared in record.rs. See, tinyset.rs for an example implementation of trait Mutator for Set64<>."

The link to record.rs doesn't work (goes here: https://github.com/vmware/differential-datalog/blob/master/rust/template/differential_datalog/record.rs)

**Comment by Kixiron** [comment]
The easiest way to implement `IntoRecord`, `FromRecord` and `Mutator` is now by using the derive macros from the `ddlog_derive` crate

**Comment by ryzhyk** [comment]
@Kixiron , right, we should add this to the tutorial since we're at it, but `ddlog_derive` is not always sufficient.  Think, e.g., some kind of custom container type.

**Comment by Kixiron** [comment]
Yes, definitely. It should suffice for the majority of cases, I'll make sure to explain them all in detail in my ddlog tutorial

**Comment by ryzhyk** [comment]
Close via 981c8371992f78658ed522a2cb23d4ce407d26ba
