### ISSUE TITLE
Is there a better pattern for joining a collection without FlatMap in the case of empty collections?

### ISSUE THREAD

**Issue by norcalli** [vmware/differential-datalog#957]
I often run into the case where I wish to join with some variable data contained inside of a collection, but I don't want to create an empty relation in the case that the collection is empty, so a FlatMap isn't what I really want here. I can usually fake this by creating an empty "base case" fact and make sure that all collections contain this base case fact so that they aren't empty, but this is obviously doing extra work that could be avoided.

One example is in trying to hierarchically evaluate a judgement on an expression tree, wherein an expression tree can be recursively evaluated by optionally summing with the results of the components, but without a way to join on iterables that isn't FlatMap, I find myself inserting an additive identity base fact (like `Judgement(Nop, 0).`) so that I can avoid having to duplicate the rule multiple times with only a slight modification for every possible edge case.

**Comment by Kixiron** [comment]
I think this was fixed by #953

**Comment by ryzhyk** [comment]
I cannot think of a better idiom to express this.  In some of my DDlog code I replace an empty collection with a singleton collection before calling `FlatMap` on it, which is slightly different, but similar in spirit to what you do.
