### ISSUE TITLE
Program crashes on duplicate commit of ddlog transaction

### ISSUE THREAD

**Issue by roymanish** [vmware/differential-datalog#967]
Ddlog should give a proper log feedback on duplicate commit of ddlog transaction. Currently it crashes the whole program with a crash dump.
There is not way to tell from the logs on why the program crashed.

**Steps to Reproduce :** 
    Inside the Java API calling ddlog program do the following :-
    1. Start a ddlog transaction `api.transactionStart();`
    2. Insert some data in ddlog tables
    3. commit the transaction. `api.transactionCommit();`
    4. Commit the transaction again and dump results. `api.transactionCommitDumpChanges`

**Crash Log Snippet** : 
`Stack: [0x00007000011bf000,0x00007000012bf000],  sp=0x00007000012be630,  free space=1021k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libddlogapi.dylib+0x168ab]  alloc::collections::btree::map::BTreeMap$LT$K$C$V$GT$::iter::ha770f86b7f997c20+0xb
C  [libddlogapi.dylib+0x3ed76]  ddlog_delta_enumerate+0x36
C  [libddlogapi.dylib+0x4b11]  Java_ddlogapi_DDlogAPI_ddlog_1transaction_1commit_1dump_1changes+0xb1
j  ddlogapi.DDlogAPI.ddlog_transaction_commit_dump_changes(JLjava/lang/String;)V+0
j  ddlogapi.DDlogAPI.transactionCommitDumpChanges(Ljava/util/function/Consumer;)V+26
j  com.vmware.mimar.transformer.service.DDLogApiService.applyMultipleTransform(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Map;+24
j  com.vmware.mimar.transformer.service.DDLogTransformService.transform(Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;)Ljava/util/Map;+33
j  com.vmware.mimar.transformer.DDlogTest.main([Ljava/lang/String;)V+46
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x39c2fe]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x21a
V  [libjvm.dylib+0x3df96c]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x11c
V  [libjvm.dylib+0x3e3164]  jni_CallStaticVoidMethod+0x1d1
C  [libjli.dylib+0x6a54]  JavaMain+0xab4
C  [libsystem_pthread.dylib+0x6950]  _pthread_start+0xe0
C  [libsystem_pthread.dylib+0x247b]  thread_start+0xf
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  ddlogapi.DDlogAPI.ddlog_transaction_commit_dump_changes(JLjava/lang/String;)V+0
j  ddlogapi.DDlogAPI.transactionCommitDumpChanges(Ljava/util/function/Consumer;)V+26
j  com.vmware.mimar.transformer.service.DDLogApiService.applyMultipleTransform(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Map;+24
j  com.vmware.mimar.transformer.service.DDLogTransformService.transform(Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;)Ljava/util/Map;+33
j  com.vmware.mimar.transformer.DDlogTest.main([Ljava/lang/String;)V+46
v  ~StubRoutines::call_stub`

**Comment by ryzhyk** [comment]
@roymanish, thanks for reporting. I will submit a PR with a fix shortly.
