### ISSUE TITLE
ddshow integration

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#973]
A recent PR introduced different profiling modes: self-profiling, where profiling events are processed by an internal thread, and external profiler where events are sent to a socket that can be connected to an external profiler like ddshow.  However, there is currently no API or CLI support for enabling the latter.

Specifically, we need:
- New Rust API method like `HDDlog::run` but with a flag to control profiling mode (or better yet, expose `differential_datalog::config::Config` through the API)
- C, Java, Go bindings
- CLI flag

On top of this, we may want another CLI switch to automatically start ddshow and connect it to the program on startup. @Kixiron, thoughts?

**Comment by Kixiron** [comment]
Yah, those sound good. I've also been working on serializing trace events to disk and then replaying that into ddshow, that could be interesting to utilize

**Comment by ryzhyk** [comment]
Closed via #1016.
