### ISSUE TITLE
Loosen restriction on `MapFunc` closure function type and also other types for more flexibility

### ISSUE THREAD

**Issue by qishen** [vmware/differential-datalog#983]
Hi, I'm trying to reuse some of the low-level DDlog APIs to run data with a tree-like data structure in the dataflow and I need less restriction on the closure function meaning I may want to pass an external variable into the `MapFunc` but the current type of `MapFunc` won't allow it. My workaround is to change the type to `MapDynFunc` shown below with dynamic dispatch and the capability to pass around between threads. 

It's very useful for situations when you need an external value passed into the closure to decide how to filter, map, or arrange the collection. Let me know what you guys think about this improvement and I can send a PR to possibly change the type of all closure functions.

```Rust
/// Function type used to map the content of a relation
/// (see `XFormCollection::Map`).
pub type MapFunc = fn(DDValue) -> DDValue;
pub type MapDynFunc = Arc<dyn Fn(DDValue) -> DDValue + Sync + Send>;

...

pub enum XFormCollection {
    ...
    /// Apply `mfun` to each element in the collection
    Map {
        description: Cow<'static, str>,
        mfun: MapDynFunc,
        next: Box<Option<XFormCollection>>,
    },
}

...

XFormCollection::Map {
    ref description,
    ref mfun,
    ref next,
} => {
    // Another workaround to avoid static lifetime for closure function.
    let mfn = mfun.clone();
    let mfn_closure = move |v: DDValue| {
        mfn.call((v,))
    };
    let mapped = with_prof_context(&description, move || col.map(mfn_closure));
    Self::streamless_xform_collection(mapped, &*next, arrangements, lookup_collection)
}

...

// We may need to pass a variable into the closure in some use cases.
let external_var = 1;
next: Box::new(Some(XFormCollection::Map {
    description: Cow::from("hello"),
    mfun: Arc::new(move |value: DDValue| -> DDValue {
        let inner_var = external_var;
        value
    }),
    next: Box::new(None)
})
```

**Comment by ryzhyk** [comment]
Hmm, this is an unusual request. The `differential-datalog` crate that contains these definitions was designed for use by ddlog-generated code and is really not meant to be used manually this way.  It lacks any kind of ergonomics and offers numerous ways to shoot yourself in the foot.  Just curious: why do you want to use this crate instead of using differential dataflow directly?

I'm not very keen on the proposed change, as it will introduce a small overhead due to `Arc` and dynamic dispatch. It's not the end of the world, but, as I mentioned above, supporting general Rust clients is not one of our design objectives for this crate.  Perhaps if I understood the use case a bit better...

@Kixiron , you've worked on this crate a lot recently.  What do you think?

**Comment by Kixiron** [comment]
I don't really have any problem with it, I was planning to do something similar in the newer version of the dataflow graph to enable fusing operations

**Comment by qishen** [comment]
Thanks for the feedback @ryzhyk . I was actually doing some experiments to see if I can re-implement an incremental core execution engine in `differential-dataflow` for [FORMULA 2.0: Formal Specifications for Verification and Synthesis](https://github.com/microsoft/formula) which can be viewed as a logic programming language. On some aspects, FORMULA has richer semantics (e.g. subterm evaluation between two tree-like data structures) than datalog languages and on other aspects FORMULA is much simpler than `differential-datalog` and does not need extern function and transformer, etc.

I came across your project and decided not to re-invent the whole wheel and theoretically I could use `differential-dataflow` directly to do the same thing but I sorta voluntarily choose to be one of the general Rust clients of ddlog ;) I'm not an expert on Rust performance but I think the proposed change won't affect the performance of the execution of ddlog program once the runtime is generated because `Arc` is just a pointer to a closure function (I could be naive and wrong)

**Comment by ryzhyk** [comment]
> Arc is just a pointer to a closure function (I could be naive and wrong)

In this case, there will be at least one extra pointer dereference compared to calling a function, which is not a big deal.

I guess I don't mind accepting the PR, but based on your description, if you don't need to use the ddlog language, you're probably better off just using differential-dataflow directly.

Do you have an example of "subterm evaluation between two tree-like data structures" that cannot be expressed in ddlog?

**Comment by qishen** [comment]
I would say Datalog is 2D and FORMULA is 3D because datalog does not support reasoning over nested data types. For example, `Edge(Node(a), Node(b))` where both `Edge` and `Node` are relations and as far as I know in DDlog you have to write something like `Edge(src: node_t, dst: node_t)` and `node_t` is a concrete type defined by the user.

**Comment by ryzhyk** [comment]
The DDlog way to write this would be:

```
relation Node(id: usize)
relation Edge(src: Node, dst: Node)
```

In any case, the `differential-datalog` crate does not provide any capabilities that are not available in DDlog that I can think of.

**Comment by qishen** [comment]
> 
> 
> The DDlog way to write this would be:
> 
> ```
> relation Node(id: usize)
> relation Edge(src: Node, dst: Node)
> ```
> 
> In any case, the `differential-datalog` crate does not provide any capabilities that are not available in DDlog that I can think of.

@ryzhyk Are you sure it works? I wrote something similar like that before but the ddlog compiler gave me errors

```
input relation N(id: u32)
input relation E(src: N, dst: N)
```

Error message: `Type argument E conflicts with user-defined type name
typedef Result<'V,'E> = Ok{res: 'V}`

**Comment by mbudiu-vmw** [comment]
Just use some longer names for the relations.
Unfortunately the code generator does not always pick fresh identifiers.
https://github.com/vmware/differential-datalog/issues/544
