### ISSUE TITLE
Rules with negation starting without positive literals does not work

### ISSUE THREAD

**Issue by qishen** [vmware/differential-datalog#995]
In one of the releases of ddlog I saw it supports rules starting without positive literals but it does not work when I write `NoCycle(u) :- not Path(u, u)` in the following program. Any ideas and workarounds?

```prolog
input relation Node(id: u32)
input relation Edge(src: Node, dst: Node)

output relation TwoEdge(src: Edge, dst: Edge)
output relation Path(src: Node, dst: Node)
output relation Line(one: Node, two: Node, three: Node, four: Node)
output relation NoCycle(node: Node)

Path(Node{a}, Node{c}) :- Path(Node{a}, Node{b}), Path(Node{b}, Node{c}).
Path(Node{a}, Node{b}) :- Edge(Node{a}, Node{b}). 
NoCycle(u) :- not Path(u, u).
```

**Comment by mbudiu-vmw** [comment]
Negation in DDlog is set difference. So it must be used in the form: `H(u) :- A(u), not B(u)`, where H will be the set difference between A and B. What would you like to have in the relation NoCycle anyway?

**Comment by ryzhyk** [comment]
The problem here is that ddlog does not allow fresh variables in negative literals. One workaround would b

NoCycle(u) :- Node(u), not Path(u,u).

**Comment by qishen** [comment]
@mbudiu-vmw `NoCycle(node: Node)` represents all the nodes that do not appear in all cyclic paths. Thanks for the clarification on the negation.

@ryzhyk Thanks for the workaround but `u` is actually of type `Node` but `NoCycle(u) :- u is Node(x), not Path(u, u).` does not work. Any other workaround except create a `Wrapper(node: Node)` relation to include all nodes and write `NoCycle(u) :- Wrapper(u), not Path(u, u).`?

**Comment by ryzhyk** [comment]
NoCycle(u) :- Node[u], not Path(u, u). 

Or

NoCycle(u) :- u in Node(), Path(u, u).

**Comment by ryzhyk** [comment]
See square brackets syntax description here: https://github.com/vmware/differential-datalog/blob/master/doc/tutorial/tutorial.md#explicit-relation-types

**Comment by qishen** [comment]
Thanks!
