### ISSUE TITLE
Can relation names or attributes with embedded 0 bytes crash the runtime?

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/differential-datalog#997]
This is based on a comment on a code review: https://github.com/vmware/differential-datalog/pull/989#discussion_r651404297

**Comment by ryzhyk** [comment]
I don't believe this is possible.  `\0` is not a valid identifier character in the DDlog grammar, so relation names containing this or any other weird characters will get rejected.  The situation is different in #989, where the string comes from a string literal.  Which can potentially contain `\0`.
